"""Crypto sends: is an outgoing crypto transfer a disposition?

The Kraken and Coinbase parsers keep every withdrawal / send / deposit
as TRANSFER custody evidence in the parse-stage sidecar
(work/<acct>_<broker>_transfers.json) — never in the books, because
moving coins between your own wallets is not a sale. A send that LEFT
your ownership (a gift, a payment for goods or services) is a
disposition at fair market value, and only the owner knows which it
was. This module:

  * pairs each send with its arrival on another exchange (a
    self-custody move, nothing to decide) and lists the rest;
  * keeps the owner's decision per send in inputs/<acct>/sends.json
    (`self` | `gift` | `payment`, plus a note), keyed by a stable id
    built from exchange, local date/time, coin and quantity (never a
    txid, refid or wallet address);
  * prices each send (the exchange's own spot price when the row has
    one; otherwise the Yahoo daily close fill-crypto uses, times the
    Bank of Canada rate of the send date) and renders the .tt line
    `BUYSELL <date> <time> <COIN> -<qty> CAD <price> <proceeds> 0`;
  * writes those lines for every gift/payment to ONE generated file,
    inputs/<acct>/crypto_sends.tt, so `taxjson run` books them;
  * for USD stablecoins (USDC/USDT/DAI, PYUSD/GUSD) — which the crypto
    books treat as US-dollar cash, so there is no coin position to sell
    — reports the currency gain instead: average CAD cost of the
    USD-cash/stablecoin pool (rebuilt from the ledgers) against the
    send-date value at the Bank of Canada rate.

The network fee a Kraken withdrawal charges in the coin is already
booked by the parser as its own disposition (`<txid>-fee`); the
sidecar quantity excludes it, so the lines here never count it again.
A matched send that arrived short with no fee stated (a Coinbase Send
carries its network fee inside the quantity) gets a `<send id>-fee`
line selling the shortfall at fair value (audit R1-26).
"""
from __future__ import annotations

import csv
import json
import math
import os
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional, Tuple

MANIFEST_NAME = "sends.json"
TT_NAME = "crypto_sends.tt"
GENERATED_MARK = ("# GENERATED by `taxjson crypto-sends --write` — do not "
                  "edit; change a decision and re-write.")
DECISIONS = ("self", "gift", "payment")
DISPOSING = ("gift", "payment")
# Decisions a country refuses: a gift is a disposition at fair value
# only in Canada (ITA s.69(1)(b)); a US donor's gift is not a sale
# (lib/country.COMMAND_COUNTRY["crypto-sends:gift"]). Checked when the
# .tt is WRITTEN, not only at --set: a sends.json carried over from a
# Canada project, copied or hand-edited must never book a US gift
# (partition SPEC-01 / INPUTS-04).
REFUSED = {"usa": ("gift",)}


class UnpricedSends(ValueError):
    """Gift/payment sends or network fees with no fair value: the .tt
    was written WITHOUT them; the caller warns (or stops under
    --strict)."""


class RefusedDecision(ValueError):
    """A saved decision the project's country refuses (a US gift). The
    .tt is still written — WITHOUT the refused sends — so nothing books
    them; the caller stops with this message."""

# USD-pegged stablecoins the crypto books treat as US-dollar cash in a
# Canada project (both parsers fold USDC/USDT/DAI/PYUSD/GUSD to USD —
# Kraken folded only the first three until audit S060-24). A sale line
# for one would sell a position that does not exist.
from taxjson.lib.brokerages._crypto_common import (  # noqa: E402
    USD_STABLECOINS as STABLECOINS)
USD_FAMILY = STABLECOINS | {"USD"}


def is_cash_stablecoin(symbol: str, exchange: str) -> bool:
    """Whether `symbol` is US-dollar cash in `exchange`'s books (the
    Canadian model, the same on every exchange; a US project books
    every stablecoin as a coin)."""
    return symbol in STABLECOINS

_EXCH_ABBR = {"kraken": "kr", "coinbase": "cb"}
_EXCH_NAME = {"kraken": "Kraken", "coinbase": "Coinbase"}
_CRYPTO_BROKERS = ("kraken", "coinbase")

# Send/arrival pairing: the arrival must land on another exchange (or
# account) within this window after the send (a little before too —
# exchange clocks disagree), with at most this share of the coins lost
# to the network fee, and never MORE coins than were sent.
MATCH_BEFORE = timedelta(minutes=10)
MATCH_AFTER = timedelta(days=3)
MATCH_MAX_LOSS = 0.10

# Superficial-loss window (ITA s.54): 30 days either side.
_SL_DAYS = 30


# ------------------------------------------------------------ formatting
def mask_ref(ref: Any) -> str:
    """First 2 characters + *** (the privacy rule for ids)."""
    s = str(ref or "").strip()
    if s.endswith("-xfer"):
        s = s[:-len("-xfer")]
    return (s[:2] + "***") if s else ""


def fmt_qty(q: float) -> str:
    """Plain decimal, no exponent, no trailing zeros (0.1, 56.821203563)."""
    s = f"{abs(float(q)):.12f}".rstrip("0").rstrip(".")
    return s or "0"


def fmt_price(p: float) -> str:
    """Six significant digits, no exponent: 387.813, 150000, 1.3611."""
    p = float(p)
    if p == 0 or not math.isfinite(p):
        return "0"
    decimals = max(6 - int(math.floor(math.log10(abs(p)))) - 1, 0)
    s = f"{round(p, decimals):.{decimals}f}"
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    return s


def send_id(exchange: str, date: str, time: str, symbol: str,
            qty: float) -> str:
    """Stable, typeable, private: kr-20260504T185014-TAO-0.1."""
    ex = _EXCH_ABBR.get(exchange, (exchange or "xx")[:2].lower())
    return (f"{ex}-{date.replace('-', '')}T{time.replace(':', '')}-"
            f"{symbol.upper()}-{fmt_qty(qty)}")


def _dt(row: Dict[str, Any]) -> datetime:
    return datetime.strptime(f"{row['date']} {row.get('time') or '00:00:00'}",
                             "%Y-%m-%d %H:%M:%S")


# ------------------------------------------------------------- evidence
_FEE_DESC_RE = re.compile(r"\(fee ([0-9.eE+-]+) ([A-Za-z0-9.]+)\)")


def load_transfer_rows(cache: Path, accounts: Iterable[str],
                       present: Optional[set] = None
                       ) -> List[Dict[str, Any]]:
    """TRANSFER evidence rows from the crypto sidecars of `accounts`.
    `present` ({(account, broker)}): only the exports still in inputs/
    — a sidecar a removed export left behind books nothing."""
    rows: List[Dict[str, Any]] = []
    for acct in accounts:
        for broker in _CRYPTO_BROKERS:
            p = cache / f"{acct}_{broker}_transfers.json"
            if not p.is_file():
                continue
            if present is not None and (acct, broker) not in present:
                continue
            try:
                doc = json.loads(p.read_text(encoding="utf-8"))
            except (OSError, ValueError) as e:
                raise ValueError(f"could not read {p.name}: {e}") from None
            meta = doc.get("metadata") or {}
            if meta.get("kind") != "transfer_sidecar":
                continue
            exch = str(meta.get("brokerage") or broker)
            for t in doc.get("transactions") or []:
                q = float(t.get("quantity") or 0.0)
                if not q or not t.get("date"):
                    continue
                desc = str(t.get("description") or "")
                sym = str(t.get("symbol") or "").upper()
                # "(fee X CCY)" names the fee and its currency (Kraken,
                # every fee since S061-17); only a fee in the coin
                # itself left the sent quantity. Older sidecars carry a
                # same-coin fee in the `fee` field instead.
                m = _FEE_DESC_RE.search(desc)
                if m:
                    fee = (float(m.group(1))
                           if m.group(2).upper() == sym else 0.0)
                else:
                    fee = float(t.get("fee") or 0.0)
                rows.append({
                    "account": acct,
                    "exchange": exch,
                    "date": str(t.get("date")),
                    "time": str(t.get("time") or "00:00:00"),
                    "symbol": sym,
                    "quantity": q,
                    "price": abs(float(t.get("price") or 0.0)),
                    "currency": str(t.get("currency") or "").upper(),
                    "fee": abs(fee),
                    "kind": desc.split(" (fee ")[0] or "transfer",
                    "ref": mask_ref(t.get("id")),
                })
    return rows


def is_hybrid_earn(row: Dict[str, Any]) -> bool:
    """A Kraken Hybrid Earn move: the coins stay on Kraken (Earn), so it
    is never an own-move to another exchange and never paired."""
    return str(row.get("kind") or "").lower().startswith("hybridearn")


def assign_send_ids(rows: List[Dict[str, Any]]) -> None:
    """Give every outgoing row its send id (``row["sid"]``). Ids have
    one-second resolution: two sends of the same coin and quantity in
    the same second on one account get ``-2``, ``-3`` ... in ledger
    order, so each keeps its own decision (re-audit A2-0586)."""
    seen: Dict[Tuple[str, str], int] = {}
    outs = [r for r in rows if r["quantity"] < 0]
    for n, r in sorted(enumerate(outs), key=lambda t: (_dt(t[1]), t[0])):
        sid = send_id(r["exchange"], r["date"], r["time"], r["symbol"],
                      r["quantity"])
        k = (r["account"], sid)
        seen[k] = seen.get(k, 0) + 1
        r["sid"] = sid if seen[k] == 1 else f"{sid}-{seen[k]}"


def _fits(o: Dict[str, Any], r: Dict[str, Any], q_in: float
          ) -> Optional[float]:
    """Seconds between send `o` and arrival `r` when `q_in` coins of
    `r` can be the arrival of `o` (another exchange or account, inside
    the window, no more than was sent, at most MATCH_MAX_LOSS lost),
    else None."""
    if r["symbol"] != o["symbol"]:
        return None
    if r["exchange"] == o["exchange"] and r["account"] == o["account"]:
        return None
    delta = _dt(r) - _dt(o)
    if delta < -MATCH_BEFORE or delta > MATCH_AFTER:
        return None
    q_out = -o["quantity"]
    if q_in > q_out * (1 + 1e-9) + 1e-12:
        return None
    if q_in < q_out * (1 - MATCH_MAX_LOSS):
        return None
    return abs(delta.total_seconds())


def _assign(costs: List[List[float]]) -> List[int]:
    """Minimum-cost assignment of every row to a distinct column
    (rows <= columns; Kuhn-Munkres, O(n^2 m)). Returns the column of
    each row."""
    n, m = len(costs), len(costs[0]) if costs else 0
    INF = float("inf")
    u, v = [0.0] * (n + 1), [0.0] * (m + 1)
    p, way = [0] * (m + 1), [0] * (m + 1)
    for i in range(1, n + 1):
        p[0] = i
        j0 = 0
        minv = [INF] * (m + 1)
        used = [False] * (m + 1)
        while True:
            used[j0] = True
            i0, delta, j1 = p[j0], INF, 0
            for j in range(1, m + 1):
                if not used[j]:
                    cur = costs[i0 - 1][j - 1] - u[i0] - v[j]
                    if cur < minv[j]:
                        minv[j], way[j] = cur, j0
                    if minv[j] < delta:
                        delta, j1 = minv[j], j
            for j in range(m + 1):
                if used[j]:
                    u[p[j]] += delta
                    v[j] -= delta
                else:
                    minv[j] -= delta
            j0 = j1
            if p[j0] == 0:
                break
        while True:
            j1 = way[j0]
            p[j0] = p[j1]
            j0 = j1
            if j0 == 0:
                break
    col = [-1] * n
    for j in range(1, m + 1):
        if p[j]:
            col[p[j] - 1] = j - 1
    return col


def stale_evidence(cache: Path,
                   broker_files: Dict[str, List[Tuple[str, Path]]],
                   skip: Iterable[str] = ()) -> List[str]:
    """Crypto accounts whose transfer sidecar does not reflect the
    exports in inputs/ (an export added or replaced since the last
    parse, or never parsed): pairing against it would call a send that
    did arrive unmatched (re-audit A2-0077 / A2-1010). One line each."""
    out: List[str] = []
    skip = set(skip)
    for acct, fs in sorted(broker_files.items()):
        if acct in skip:
            continue
        for broker in _CRYPTO_BROKERS:
            csvs = [p for b, p in fs if b == broker]
            if not csvs:
                continue
            side = cache / f"{acct}_{broker}_transfers.json"
            if not side.is_file():
                out.append(f"{acct} ({broker}: not parsed yet)")
                continue
            t = side.stat().st_mtime
            newer = [p.name for p in csvs if p.stat().st_mtime > t]
            if newer:
                out.append(f"{acct} ({', '.join(newer)} changed since the "
                           f"last parse)")
    return out


def match_transfers(rows: List[Dict[str, Any]],
                    unpaired: Iterable[Tuple[str, str]] = ()
                    ) -> Tuple[List[Dict[str, Any]],
                               List[Tuple[Dict[str, Any], Dict[str, Any]]]]:
    """(unmatched sends, [(send, arrival)]). Each send is paired with at
    most one arrival and vice versa: same coin, another exchange or
    account, from MATCH_BEFORE before to MATCH_AFTER after the send,
    arrival <= sent and within the network-fee loss.

    The pairing is a minimum-loss ASSIGNMENT per coin, not first come
    first served (re-audit A2-0078 / A2-0239): as many sends as possible
    are paired, then the fewest coins lost, then the closest in time —
    a send never takes an arrival that fits another send better.
    Leftovers then try a split: one send that landed as two deposits,
    or two sends that landed as one (A2-1006); the arrival returned
    for those is a synthetic row whose ``parts`` are the real ones.

    Never paired: a Kraken Hybrid Earn move (the coins stay on Kraken,
    A2-0573) and a send the owner unpaired (``unpaired``: (account,
    send id) pairs saved with ``--unpair``, A2-0004)."""
    if any("sid" not in r for r in rows if r["quantity"] < 0):
        assign_send_ids(rows)
    unpaired = set(unpaired)
    outs = sorted((r for r in rows if r["quantity"] < 0),
                  key=lambda r: (_dt(r), r["exchange"], r["symbol"]))
    # Arrivals keep the evidence order: on a full tie the first wins.
    ins = [r for r in rows if r["quantity"] > 0 and not is_hybrid_earn(r)]
    pairable = [o for o in outs if not is_hybrid_earn(o)
                and (o["account"], o.get("sid")) not in unpaired]
    paired: Dict[int, Dict[str, Any]] = {}
    used: set = set()
    for sym in sorted({o["symbol"] for o in pairable}):
        so = [o for o in pairable if o["symbol"] == sym]
        si = [r for r in ins if r["symbol"] == sym]
        if not si:
            continue
        top = max(-o["quantity"] for o in so) or 1.0
        span = MATCH_AFTER.total_seconds() + MATCH_BEFORE.total_seconds()
        BIG = 1e6                  # one more pair always beats any loss
        costs = []
        for k, o in enumerate(so):
            row = []
            for r in si:
                secs = _fits(o, r, r["quantity"])
                row.append(float("inf") if secs is None else
                           1000.0 * (-o["quantity"] - r["quantity"]) / top
                           + secs / span)
            row += [BIG if j == k else float("inf")
                    for j in range(len(so))]
            costs.append(row)
        for k, j in enumerate(_assign(costs)):
            if 0 <= j < len(si):
                paired[id(so[k])] = si[j]
                used.add(id(si[j]))
    # Splits, on what is left: one send -> two arrivals, then two
    # sends -> one arrival (each send gets its share of the arrival).
    free_in = [r for r in ins if id(r) not in used]
    for o in pairable:
        if id(o) in paired:
            continue
        q_out, best = -o["quantity"], None
        cand = [r for r in free_in if id(r) not in used
                and r["quantity"] < q_out
                and _fits(o, r, q_out) is not None]
        for a in range(len(cand)):
            for b in range(a + 1, len(cand)):
                q = cand[a]["quantity"] + cand[b]["quantity"]
                last = max(cand[a], cand[b], key=_dt)
                secs = _fits(o, last, q)
                if secs is None:
                    continue
                key = (q_out - q, secs)
                if best is None or key < best[0]:
                    best = (key, cand[a], cand[b])
        if best:
            _k, a, b = best
            used.update((id(a), id(b)))
            paired[id(o)] = dict(a, quantity=a["quantity"] + b["quantity"],
                                 parts=[a, b])
    left = [o for o in pairable if id(o) not in paired]
    for r in free_in:
        if id(r) in used:
            continue
        best = None
        for x in range(len(left)):
            for y in range(x + 1, len(left)):
                o1, o2 = left[x], left[y]
                if id(o1) in paired or id(o2) in paired:
                    continue
                if o1["account"] != o2["account"]:
                    continue
                both = dict(o1, quantity=o1["quantity"] + o2["quantity"])
                secs = _fits(both, r, r["quantity"])
                if secs is None or _fits(dict(o2, quantity=both["quantity"]),
                                         r, r["quantity"]) is None:
                    continue
                key = (-both["quantity"] - r["quantity"], secs)
                if best is None or key < best[0]:
                    best = (key, o1, o2)
        if best:
            _k, o1, o2 = best
            used.add(id(r))
            tot = -(o1["quantity"] + o2["quantity"])
            for o in (o1, o2):
                paired[id(o)] = dict(r, quantity=r["quantity"]
                                     * -o["quantity"] / tot, parts=[r])
    unmatched = [o for o in outs if id(o) not in paired]
    pairs = [(o, paired[id(o)]) for o in outs if id(o) in paired]
    return unmatched, pairs


def arrival_rows(arrival: Dict[str, Any]) -> List[Dict[str, Any]]:
    """The real sidecar rows behind a paired arrival (a split arrival
    is a synthetic row over its ``parts``)."""
    return list(arrival.get("parts") or [arrival])


# ------------------------------------------------------------- manifest
# A hand price below this cannot be told apart from "no price" by
# fill-crypto (it re-prices the line from Yahoo), so it is refused.
MIN_PRICE = 1e-8
# The decision a `<send id>-fee` entry (a network fee hidden in a send
# that arrived short) takes when the owner prices it by hand.
FEE_DECISION = "fee"


def price_problem(price: Any) -> Optional[str]:
    """Why `price` is not a usable hand price per coin (None: it is)."""
    if isinstance(price, bool) or not isinstance(price, (int, float)):
        return f"{price!r} is not a number"
    if not math.isfinite(price):
        return f"{price!r} is not a finite number"
    if price < MIN_PRICE:
        return (f"{price!r} is not a positive value of at least "
                f"{MIN_PRICE:.8f} per coin")
    return None


def load_decisions(path: Path) -> Dict[str, Any]:
    if not path.is_file():
        return {"schema_version": 1, "sends": {}}
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        raise ValueError(f"{path} is not valid JSON ({e}) — fix or delete "
                         f"it (it holds your gift/payment/self decisions)."
                         ) from None
    if not isinstance(doc, dict) or not isinstance(doc.get("sends"), dict):
        raise ValueError(f"{path}: expected {{\"sends\": {{ID: {{...}}}}}}.")
    for sid, rec in doc["sends"].items():
        ok = (DECISIONS + (FEE_DECISION,) if str(sid).endswith("-fee")
              else DECISIONS)
        if not isinstance(rec, dict) or rec.get("decision") not in ok:
            raise ValueError(
                f"{path}: send {sid!r} has decision "
                f"{(rec or {}).get('decision') if isinstance(rec, dict) else rec!r}"
                f" — expected one of {', '.join(ok)}.")
        # A hand-edited price is checked like --price: NaN/0/Infinity
        # booked a 0-proceeds sale, a negative one broke convert-tt, a
        # string dropped the line with a WARNING (re-audit A2-0241).
        if "price" in rec and rec["price"] is not None:
            why = price_problem(rec["price"])
            if why:
                raise ValueError(
                    f"{path}: send {sid!r} has price {why} — fix it or "
                    f"remove the \"price\" key (the fair value is then "
                    f"looked up).")
        if rec.get("decision") == FEE_DECISION and rec.get("price") is None:
            raise ValueError(f"{path}: send {sid!r} is `{FEE_DECISION}` "
                             f"without a price — give one or remove it.")
        if "unpair" in rec and not isinstance(rec["unpair"], bool):
            raise ValueError(f"{path}: send {sid!r} has unpair "
                             f"{rec['unpair']!r} — expected true or false.")
    doc.setdefault("schema_version", 1)
    return doc


def save_decisions(path: Path, doc: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".part")
    # Strict JSON: an Infinity/NaN never reaches the manifest.
    tmp.write_text(json.dumps(doc, indent=2, sort_keys=True,
                              allow_nan=False) + "\n",
                   encoding="utf-8")
    os.replace(tmp, path)


def record_decision(path: Path, sid: str, decision: str,
                    note: Optional[str] = None,
                    price: Optional[float] = None,
                    summary: str = "",
                    unpair: Optional[bool] = None) -> None:
    """Save one decision. A hand price belongs to the decision it was
    given with: re-deciding a send to ANOTHER decision without --price
    drops it, so a typo is never stuck (re-audit A2-0572). `unpair`
    True keeps the send out of the automatic pairing (A2-0004)."""
    ok = (DECISIONS + (FEE_DECISION,) if sid.endswith("-fee")
          else DECISIONS)
    if decision not in ok:
        raise ValueError(f"decision {decision!r} — expected one of "
                         f"{', '.join(ok)}")
    if price is not None:
        why = price_problem(price)
        if why:
            raise ValueError(f"--price {why}.")
    doc = load_decisions(path)
    rec = dict(doc["sends"].get(sid) or {})
    if price is None and rec.get("decision") != decision:
        rec.pop("price", None)
    rec["decision"] = decision
    if summary:
        rec["summary"] = summary
    if note is not None:
        if note:
            rec["note"] = note
        else:
            rec.pop("note", None)
    if price is not None:
        rec["price"] = float(price)
    if unpair is not None:
        if unpair:
            rec["unpair"] = True
        else:
            rec.pop("unpair", None)
    doc["sends"][sid] = rec
    save_decisions(path, doc)


def clear_decision(path: Path, sid: str) -> bool:
    """Remove a saved decision (the send is undecided again: `run`
    asks, the checklist lists it). False when none was saved."""
    doc = load_decisions(path)
    if sid not in doc["sends"]:
        return False
    doc["sends"].pop(sid)
    save_decisions(path, doc)
    return True


# ---------------------------------------------------------------- rates
def load_rates(path: Path) -> Dict[str, Dict[str, Tuple[float, str]]]:
    """{currency: {date: (rate, source)}} from work/to_base.csv
    (`DATE TIME FROM TO RATE [SOURCE]`), read like convert-currency
    reads it (re-audit A2-0999): a rate that parses but is not a
    positive finite number (NaN, 0, a negative) is refused — it used to
    be skipped and the send priced at an earlier day's rate without a
    word; an unreadable rate is skipped with a warning; the FIRST row of
    a currency and date wins (the noon row, not today's spot row)."""
    out: Dict[str, Dict[str, Tuple[float, str]]] = {}
    if not path.is_file():
        return out
    bad: List[str] = []
    for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(),
                             1):
        parts = line.split()
        if len(parts) < 5 or not re.match(r"^\d{4}-\d{2}-\d{2}$", parts[0]):
            continue
        try:
            rate = float(parts[4])
        except ValueError:
            bad.append(f"line {n}: {line.strip()!r}")
            continue
        if not (rate > 0 and math.isfinite(rate)):
            raise ValueError(
                f"rates file {path}, line {n}: rate {parts[4]!r} for "
                f"{parts[2]}->{parts[3]} on {parts[0]} is not a positive "
                f"finite number — refusing to value a send with it. Fix "
                f"or regenerate the rates file (`taxjson run`).")
        out.setdefault(parts[2].upper(), {}).setdefault(parts[0], (
            rate, parts[5].lower() if len(parts) > 5 else ""))
    if bad:
        print(f"taxjson crypto-sends: warning: {path.name}: skipped "
              f"{len(bad)} line(s) with an unreadable rate (e.g. "
              f"{bad[0]}).", file=sys.stderr)
    return out


class Rates:
    def __init__(self, table, base: str):
        self.table = table
        self.base = base.upper()
        self._sorted: Dict[str, List[str]] = {}

    def get(self, cur: str, on: str) -> Optional[Tuple[float, str, str]]:
        """(rate, rate date, label) of the latest rate on/before `on`."""
        cur = cur.upper()
        if cur == self.base:
            return 1.0, on, ""
        days = self.table.get(cur) or {}
        if cur not in self._sorted:
            self._sorted[cur] = sorted(days)
        keys = self._sorted[cur]
        import bisect
        i = bisect.bisect_right(keys, on)
        if i == 0:
            return None
        d = keys[i - 1]
        rate, src = days[d]
        label = {"boc": "Bank of Canada", "irs": "IRS"}.get(src, src or "")
        return rate, d, label


def _rate_text(cur: str, base: str, r: Tuple[float, str, str],
               on: str) -> str:
    rate, d, label = r
    who = f"{label} " if label else ""
    when = d if d == on else f"{d}, latest before {on}"
    return f"{who}{cur}/{base} {rate:g} ({when})"


# ---------------------------------------------------------------- prices
def yahoo_usd_price(project_root: Path) -> Callable[[str, str],
                                                    Tuple[Optional[float], str]]:
    """The fill-crypto price source: Yahoo `<id>-USD` daily close, the
    same cache (~/.crypto_price_cache.json) and the same symbol map
    (built-ins + the project's crypto_ticker.map). Offline
    (TAXJSON_OFFLINE) it answers from the cache only."""
    from taxjson.bin import fill_crypto_prices as F
    from taxjson.lib.offline import offline_enabled
    # The same folders, in the same order, as `taxjson run` gives
    # fill-crypto: the project root, then the folder of its input file
    # (work/) — later wins (re-audit A2-0242).
    overrides = F.load_symbol_overrides([str(project_root),
                                         str(Path(project_root) / "work")])
    state: Dict[str, Any] = {"cache": None}

    def lookup(symbol: str, day: str) -> Tuple[Optional[float], str]:
        ysym = overrides.get(symbol, symbol)
        if state["cache"] is None:
            state["cache"] = F.load_cache()
        cache = state["cache"]
        key = f"{ysym}-{day}"
        # A damaged entry (null, "abc", true, Infinity) is a miss, as in
        # fill-crypto (re-audit A2-0464 / A2-1403).
        hit = F.cached_price(cache, key)
        if hit is not None:
            return hit, ysym
        if offline_enabled():
            return None, ysym
        saved = dict(F.SYMBOL_OVERRIDES)
        F.SYMBOL_OVERRIDES.update(overrides)
        try:
            p = F.get_crypto_price(symbol, day)
        finally:
            F.SYMBOL_OVERRIDES.clear()
            F.SYMBOL_OVERRIDES.update(saved)
        if p and p > 0:
            # A close for UTC today or later is the still-open candle:
            # used, never cached (fill-crypto's rule, audit S025-08 —
            # this shared cache re-opened it, re-audit A2-0570).
            if day < F._utc_today():
                cache[key] = p
                F.save_cache(cache)
            return float(p), ysym
        return None, ysym
    return lookup


def fair_value(send: Dict[str, Any], rates: Rates,
               usd_price: Optional[Callable[[str, str],
                                            Tuple[Optional[float], str]]],
               manual: Optional[float] = None,
               stable_cash: bool = True) -> Optional[Dict[str, Any]]:
    """{'price': per coin in base, 'value', 'source'} or None (unpriced).
    `stable_cash`: stablecoins are US-dollar cash in the books (Canada);
    False (a US project) prices one at its 1.00 USD par as property."""
    base = rates.base
    sym, day, qty = send["symbol"], send["date"], -send["quantity"]
    ex = _EXCH_NAME.get(send["exchange"], send["exchange"])
    if manual is not None:
        price, src = float(manual), "entered by hand (--price)"
    elif sym in STABLECOINS and (not stable_cash or is_cash_stablecoin(
            sym, send.get("exchange", ""))):
        r = rates.get("USD", day)
        if r is None:
            return None
        price = r[0]
        src = ((f"{sym} = 1 USD (stablecoins are US-dollar cash in the "
                f"books)" if stable_cash else
                f"{sym} at its 1.00 USD par")
               + ("" if base == "USD" else
                  f" x {_rate_text('USD', base, r, day)}"))
    elif send["price"] > 0:
        cur = send["currency"] or "USD"
        cur = "USD" if cur in STABLECOINS else cur
        if cur == base:
            price = send["price"]
            src = f"{ex} spot price on the send row ({base})"
        else:
            r = rates.get(cur, day)
            if r is None:
                return None
            price = send["price"] * r[0]
            src = (f"{ex} spot price {fmt_price(send['price'])} {cur} x "
                   f"{_rate_text(cur, base, r, day)}")
    else:
        if usd_price is None:
            return None
        usd, ysym = usd_price(sym, day)
        if not usd:
            return None
        if base == "USD":
            price = usd
            src = f"Yahoo {ysym}-USD daily close {fmt_price(usd)} USD ({day})"
        else:
            r = rates.get("USD", day)
            if r is None:
                return None
            price = usd * r[0]
            src = (f"Yahoo {ysym}-USD daily close {fmt_price(usd)} USD "
                   f"({day}) x {_rate_text('USD', base, r, day)}")
    p = float(fmt_price(price))
    return {"price": p, "value": round(qty * p, 2), "currency": base,
            "source": src}


def tt_line(send: Dict[str, Any], fv: Dict[str, Any], base: str) -> str:
    qty = -send["quantity"]
    return (f"BUYSELL {send['date']} {send['time']} {send['symbol']} "
            f"-{fmt_qty(qty)} {base} {fmt_price(fv['price'])} "
            f"{round(qty * fv['price'], 2):.2f} 0")


# ------------------------------------------------ USD / stablecoin pool
def _kraken_norm(asset: str, fold: bool = False) -> str:
    from taxjson.lib.brokerages.kraken import _normalize_asset
    return _normalize_asset(asset, fold_stable=fold)


def kraken_pool_flows(path: Path) -> List[Dict[str, Any]]:
    """USD-family cash flows from one Kraken LEDGER export, one per
    refid: {'dt', 'units' (signed), 'cad' (CAD leg of the same refid)}.
    Custody rows (withdrawal/deposit/p2p/hybridearnwithdrawal of a
    non-fiat asset) are skipped — they come from the sidecar with their
    pairing — and so are Earn-wallet shuffles (never left the account)."""
    from taxjson.lib.brokerages.kraken import (
        _classify_header, _fee_ccy, _lower_row, _STAKING_WALLET_MOVES,
        _FIAT_CURRENCIES)
    from taxjson.lib.brokerages._crypto_common import (strict_money,
                                                       utc_to_local)
    import io
    from taxjson.lib.brokerages.base import read_broker_text
    from taxjson.lib.brokerages.kraken import _dict_rows
    # The parser's reader: UTF-16 re-saves, a duplicated column and a
    # cell holding a line break are handled as the parser handles them.
    with io.StringIO(read_broker_text(path)) as f:
        if _classify_header(f.readline()) != "ledgers":
            return []
        f.seek(0)
        groups: Dict[str, Dict[str, Any]] = {}
        order: List[str] = []
        for n, (raw, _line) in enumerate(_dict_rows(f, path, "ledger")):
            row = _lower_row(raw)
            type_ = (row.get("type") or "").strip().lower()
            sub = (row.get("subtype") or "").strip().lower()
            name = _kraken_norm(row.get("asset") or "")
            if (type_ in ("withdrawal", "deposit", "hybridearnwithdrawal")
                    or (type_ == "transfer" and sub == "transferpeertopeer")
                    ) and name not in _FIAT_CURRENCIES:
                continue            # custody evidence -> the sidecar
            if ((type_ == "earn" and sub in ("allocation", "deallocation",
                                             "autoallocation"))
                    or (type_.startswith("hybridearn"))
                    or (type_ == "transfer" and sub in _STAKING_WALLET_MOVES)):
                continue            # own-wallet shuffle
            amount = strict_money(row.get("amount"), "amount", path.name)
            fee = abs(strict_money(row.get("fee"), "fee", path.name))
            fccy = _fee_ccy(row, name)
            fam = ((amount if name in USD_FAMILY else 0.0)
                   - (fee if fccy in USD_FAMILY else 0.0))
            cad = ((amount if name == "CAD" else 0.0)
                   - (fee if fccy == "CAD" else 0.0))
            if not fam and not cad:
                continue
            ref = (row.get("refid") or "").strip() or f"#{n}"
            g = groups.get(ref)
            if g is None:
                t = (row.get("time") or "").split(".")[0]
                dt = utc_to_local(datetime.strptime(t, "%Y-%m-%d %H:%M:%S"))
                g = groups[ref] = {"dt": dt, "units": 0.0, "cad": 0.0,
                                   "what": f"Kraken {type_}"}
                order.append(ref)
            g["units"] += fam
            g["cad"] += cad
    return [groups[r] for r in order if abs(groups[r]["units"]) > 1e-9]


def coinbase_pool_flows(path: Path) -> List[Dict[str, Any]]:
    """Stablecoin flows from one Coinbase export: buys/sells/rewards of
    a stablecoin, and the stablecoin leg of Advanced Trades on X-USDC
    and of Converts. Send/Receive come from the sidecar."""
    from taxjson.lib.brokerages import coinbase as C
    from taxjson.lib.brokerages._crypto_common import (strict_money,
                                                       utc_to_local)
    out: List[Dict[str, Any]] = []
    import io
    from taxjson.lib.brokerages.base import read_broker_text
    with io.StringIO(read_broker_text(path)) as f:
        rows = list(csv.reader(f))
    hmap: Dict[str, int] = {}
    start = None
    for i, row in enumerate(rows):
        if row and "timestamp" in [c.lower().strip() for c in row]:
            raw = {c.lower().strip(): j for j, c in enumerate(row)}
            for field, names in C._HEADER_SYNONYMS.items():
                for nm in names:
                    if nm in raw:
                        hmap[field] = raw[nm]
                        break
            start = i + 1
            break
    if start is None:
        return out

    def col(row, key):
        j = hmap.get(key, -1)
        return row[j] if 0 <= j < len(row) else ""

    def num(row, key):
        return strict_money(col(row, key), key, path.name)

    for row in rows[start:]:
        if not row or len(row) < 3:
            continue
        type_raw = col(row, "transaction type").strip()
        tl = type_raw.lower()
        if tl in ("send", "receive"):
            continue
        stamp = col(row, "timestamp").replace(" UTC", "").strip()
        dt = None
        for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%SZ"):
            try:
                dt = datetime.strptime(stamp, fmt)
                break
            except ValueError:
                continue
        if dt is None:
            continue
        dt = utc_to_local(dt)
        asset = col(row, "asset").strip().upper()
        cur = (col(row, "price currency") or "USD").strip().upper()
        notes = col(row, "notes") or ""
        ctx = f"{path.name} Notes {notes!r}"
        if "convert" in tl:
            # One row carries BOTH legs in its Notes, and Coinbase names
            # either leg in the Asset column (the parser accepts both):
            # read the stablecoin flow from the Notes alone, so the same
            # Convert moves the pool the same way whichever leg the
            # Asset column names (re-audit A2-0243 / A2-0574). Numbers
            # go through the strict reader: '0,125' is a decimal comma,
            # never 125 (A2-1008).
            m = C._CONVERT_NOTES_RE.search(notes)
            if m:
                units = 0.0
                if m.group(2).upper() in STABLECOINS:
                    units -= strict_money(m.group(1), "Convert quantity",
                                          ctx)
                if m.group(4).upper() in STABLECOINS:
                    units += strict_money(m.group(3), "Convert quantity",
                                          ctx)
                if units:
                    out.append({"dt": dt, "units": units, "cad": 0.0,
                                "what": "Coinbase Convert"})
            continue
        if asset in STABLECOINS:
            qty = abs(num(row, "quantity transacted"))
            if C._STAKING_RE.search(type_raw):
                out.append({"dt": dt, "units": qty, "cad": 0.0,
                            "what": f"Coinbase {type_raw}"})
            elif C._BUY_RE.search(type_raw):
                total = abs(num(row, "total")) if col(row, "total") else 0.0
                out.append({"dt": dt, "units": qty,
                            "cad": -total if cur == "CAD" else 0.0,
                            "what": f"Coinbase {type_raw}"})
            elif C._SELL_RE.search(type_raw):
                out.append({"dt": dt, "units": -qty, "cad": 0.0,
                            "what": f"Coinbase {type_raw}"})
            continue
        m = C._ADV_NOTES_RE.search(notes)
        if m and m.group(5).upper() in STABLECOINS:
            n = strict_money(m.group(4), "Advanced Trade quantity", ctx)
            out.append({"dt": dt,
                        "units": -n if m.group(1).lower() == "bought" else n,
                        "cad": 0.0, "what": f"Coinbase {type_raw}"})
    return out


def usd_pool(flows: List[Dict[str, Any]], transfers: List[Dict[str, Any]],
             pairs, unmatched_ids: Dict[int, str], rates: Rates
             ) -> Dict[str, Any]:
    """Walk the USD-cash/stablecoin pool (average cost, ITA s.47) and
    value every unmatched stablecoin send against it.

    Acquisitions: a CAD leg in the same ledger entry is the exact cost
    (a CAD->USDC conversion); anything else (USD from a crypto sale, a
    stablecoin reward, a deposit from outside) costs units x the rate of
    the day. A send paired with its arrival only loses the network fee;
    an unmatched send leaves at average cost and, when it is a
    stablecoin, its FX gain is value - ACB."""
    base = rates.base
    events: List[Tuple[datetime, int, str, Dict[str, Any]]] = []
    for f in flows:
        events.append((f["dt"], 1, "flow", f))
    paired = {id(o): i for o, i in pairs}
    paired_in = {id(r) for _o, i in pairs for r in arrival_rows(i)}
    for t in transfers:
        if t["symbol"] not in USD_FAMILY:
            continue
        if t["quantity"] > 0:
            # A paired arrival is the same coins coming back: only its
            # deposit fee leaves the pool (re-audit A2-1011).
            events.append((_dt(t), 1, "in-paired" if id(t) in paired_in
                           else "in", t))
        else:
            events.append((_dt(t), 2, "out", t))
    events.sort(key=lambda e: (e[0], e[1]))
    units = cost = 0.0
    overdrafts = 0
    unrated = 0
    acq_dates: List[str] = []
    after: List[Tuple[str, float]] = []
    results: Dict[str, Dict[str, Any]] = {}

    def rate(day: str) -> Optional[float]:
        r = rates.get("USD", day)
        return r[0] if r else None

    def dispose(n: float, day: str) -> Tuple[float, float]:
        """Remove n units; returns (acb, overdraft units)."""
        nonlocal units, cost, overdrafts
        covered = min(n, units)
        acb = 0.0
        if covered > 0:
            avg = cost / units
            acb = covered * avg
            units -= covered
            cost -= acb
            if units < 1e-9:
                units, cost = 0.0, 0.0
        short = n - covered
        if short > 1e-6:
            overdrafts += 1
        return acb, max(short, 0.0)

    for dt, _o, kind, e in events:
        day = dt.strftime("%Y-%m-%d")
        if kind == "in-paired":
            if e.get("fee"):
                dispose(e["fee"], day)
            after.append((day, units))
            continue
        if kind in ("flow", "in"):
            n = e["units"] if kind == "flow" else e["quantity"]
            if n > 0:
                if kind == "flow" and e.get("cad", 0.0) < 0:
                    c = -e["cad"]
                else:
                    r = rate(day)
                    if r is None:
                        unrated += 1
                        continue
                    c = n * r
                units += n
                cost += c
                acq_dates.append(day)
                # A deposit's fee (taken in the coin on arrival) leaves
                # the pool too: the ledger credits only n - fee
                # (re-audit A2-0592).
                if kind == "in" and e.get("fee"):
                    dispose(e["fee"], day)
            else:
                dispose(-n, day)
        else:                                            # an out-leg
            q = -e["quantity"]
            if id(e) in paired:
                lost = q - paired[id(e)]["quantity"]
                if lost > 0:
                    dispose(lost, day)
            else:
                acb, short = dispose(q, day)
                r = rate(day)
                sid = unmatched_ids.get(id(e))
                if sid and e["symbol"] in STABLECOINS and r is not None:
                    acb += short * r      # overdraft: zero gain on it
                    value = q * r
                    results[sid] = {"units": q, "rate": r,
                                    "value": round(value, 2),
                                    "acb": round(acb, 2),
                                    "gain": round(value - acb, 2),
                                    "overdrawn": short > 1e-6}
            if e.get("fee"):
                dispose(e["fee"], day)
        after.append((day, units))

    # Superficial-loss flag (s.54): a loss, the same property bought
    # within 30 days either side, still held on day 30.
    for sid, res in results.items():
        res["superficial"] = False
        if res["gain"] >= 0:
            continue
        send_day = next(t for t in transfers
                        if unmatched_ids.get(id(t)) == sid)["date"]
        d0 = datetime.strptime(send_day, "%Y-%m-%d")
        lo = (d0 - timedelta(days=_SL_DAYS)).strftime("%Y-%m-%d")
        hi = (d0 + timedelta(days=_SL_DAYS)).strftime("%Y-%m-%d")
        if not any(lo <= d <= hi for d in acq_dates):
            continue
        held = 0.0
        for d, u in after:
            if d <= hi:
                held = u
        res["superficial"] = held > 1e-9
    return {"results": results, "overdrafts": overdrafts,
            "unrated": unrated, "units_now": round(units, 6),
            "avg_cost": (round(cost / units, 6) if units > 1e-9 else None),
            "base": base}


# --------------------------------------------------------------- report
def _summary(s: Dict[str, Any]) -> str:
    ex = _EXCH_NAME.get(s["exchange"], s["exchange"])
    return (f"{ex} {s['kind']} {s['date']} {s['time']} "
            f"{fmt_qty(-s['quantity'])} {s['symbol']}")


def crypto_accounts(cfg: Dict[str, Any]) -> List[str]:
    return [n for n, a in (cfg.get("accounts") or {}).items()
            if (a or {}).get("crypto")]


def build_report(root: Path, cfg: Dict[str, Any],
                 broker_files: Optional[Dict[str, List[Tuple[str, Path]]]]
                 = None,
                 usd_price=None, want: Optional[str] = None,
                 with_pool: bool = True,
                 exports_only: bool = False) -> Dict[str, Any]:
    """Everything `crypto-sends` shows, per crypto account.
    `broker_files` ({acct: [(broker, csv)]}) feeds the stablecoin pool;
    None skips it (the checklist needs only the decisions).
    `exports_only`: `broker_files` lists EVERY export in inputs/, and a
    sidecar left by a removed export is ignored (re-audit A2-1026)."""
    settings = cfg.get("settings") or {}
    from taxjson.lib.country import home_currency, settings_country
    country = settings_country(settings)
    base = str(settings.get("base_currency")
               or home_currency(country)).upper()
    cache = root / "work"
    accts = crypto_accounts(cfg)
    present = None
    if exports_only and broker_files is not None:
        present = {(a, b) for a, fs in broker_files.items() for b, _p in fs}
    rows = load_transfer_rows(cache, accts, present)
    assign_send_ids(rows)
    man_paths = {a: root / "inputs" / a / MANIFEST_NAME for a in accts}
    all_decisions = {a: load_decisions(p)["sends"]
                     for a, p in man_paths.items()}
    unpaired = {(a, sid) for a, d in all_decisions.items()
                for sid, rec in d.items() if rec.get("unpair")}
    unmatched, pairs = match_transfers(rows, unpaired)
    rates = Rates(load_rates(cache / "to_base.csv"), base)
    ids: Dict[int, str] = {id(s): s["sid"] for s in unmatched}
    pool = None
    if with_pool and broker_files is not None and base != "USD" and any(
            is_cash_stablecoin(s["symbol"], s["exchange"])
            for s in unmatched):
        flows: List[Dict[str, Any]] = []
        for acct in accts:
            for broker, p in broker_files.get(acct, []):
                if broker == "kraken":
                    flows += kraken_pool_flows(p)
                elif broker == "coinbase":
                    flows += coinbase_pool_flows(p)
        pool = usd_pool(flows, rows, pairs, ids, rates)
    out: Dict[str, Any] = {"base_currency": base, "country": country,
                           "accounts": {}}
    for acct in accts:
        if want and acct != want:
            continue
        man_path = man_paths[acct]
        decisions = all_decisions[acct]
        sends = []
        for s in sorted((s for s in unmatched if s["account"] == acct),
                        key=lambda s: (_dt(s), ids[id(s)])):
            sid = ids[id(s)]
            rec = decisions.get(sid) or {}
            if not rec and is_hybrid_earn(s):
                # Kraken Hybrid Earn: the coins leave the spot ledger for
                # Kraken's Earn product and keep earning rewards for you —
                # still your property. Decided automatically; --set
                # overrides it.
                rec = {"decision": "self", "auto": True,
                       "note": "Kraken Hybrid Earn: still yours "
                               "(automatic)"}
            # A US project books stablecoins as property (tax-logic
            # US-CRYPTO-02): a gift/payment of one is a sale line like
            # any coin's. Canada keeps them US-dollar cash (CA-CRYPTO-08).
            stable = (is_cash_stablecoin(s["symbol"], s["exchange"])
                      and country != "usa")
            fv = fair_value(s, rates, usd_price, rec.get("price"),
                            stable_cash=country != "usa")
            entry = {
                "id": sid, "account": acct, "exchange": s["exchange"],
                "kind": s["kind"], "date": s["date"], "time": s["time"],
                "symbol": s["symbol"], "quantity": -s["quantity"],
                "fee_booked": s["fee"], "ref": s["ref"],
                "summary": _summary(s), "stable": stable,
                "decision": rec.get("decision"), "note": rec.get("note", ""),
                "auto": bool(rec.get("auto")),
                "unpaired": bool(rec.get("unpair")),
                "fair_value": fv, "tt": None, "fx": None,
            }
            if rec.get("decision") in REFUSED.get(country, ()):
                entry["refused"] = (
                    f"{sid} is saved as `{rec['decision']}`, which a US "
                    f"project refuses: a gift is not a sale for a US donor "
                    f"(the recipient takes over your basis). It is NOT "
                    f"booked — record it as `self` (no tax event) or, if "
                    f"you were paid, `payment`: `taxjson crypto-sends "
                    f"{acct} --set {sid}=self`")
            if not stable and fv is not None:
                entry["tt"] = tt_line(s, fv, base)
            if stable and pool is not None:
                entry["fx"] = pool["results"].get(sid)
            sends.append(entry)
        fees = network_fees(pairs, acct, rates, usd_price, country,
                            decisions)
        live = {e["id"] for e in sends} | {e["id"] for e in fees}
        mine = [(o, i) for o, i in pairs if o["account"] == acct]
        matched_ids = {o["sid"]: (o, i) for o, i in mine}
        # A saved gift/payment for a send that now PAIRS with an
        # arrival: the pairing books it as your own move, so the
        # decision no longer counts — said in the run, the checklist
        # and the listing, never only here (re-audit A2-0004).
        overridden = []
        for sid, rec in sorted(decisions.items()):
            if sid in matched_ids and rec.get("decision") in DISPOSING:
                o, i = matched_ids[sid]
                overridden.append({
                    "id": sid, "decision": rec["decision"],
                    "summary": _summary(o),
                    "arrival": (f"{fmt_qty(i['quantity'])} {i['symbol']} "
                                f"on {_EXCH_NAME.get(i['exchange'], i['exchange'])}"
                                f" ({i['account']}) {i['date']} {i['time']}")})
        # US: basis is per account (US-BASIS-01) and nothing carries a
        # moved lot's basis and holding period from one account to
        # another, so a paired move between two crypto accounts leaves
        # a short on one side and a phantom long on the other
        # (re-audit A2-0003): listed so the run can stop.
        cross = []
        if country == "usa":
            for o, i in mine:
                dest = {r["account"] for r in arrival_rows(i)}
                if dest - {acct}:
                    cross.append({
                        "id": o["sid"], "summary": _summary(o),
                        "to": sorted(dest - {acct})})
        out["accounts"][acct] = {
            "sends": sends,
            "matched": len(mine),
            "undecided": sum(1 for e in sends if not e["decision"]),
            "orphans": sorted(k for k in decisions
                              if k not in live and k not in matched_ids),
            "overridden": overridden,
            "cross_account_moves": cross,
            "network_fees": fees,
            "manifest": str(man_path),
            "tt_file": str(root / "inputs" / acct / TT_NAME),
        }
    if pool is not None:
        out["pool"] = {k: v for k, v in pool.items() if k != "results"}
    return out


def matched_send(report_rows_root: Path, cfg: Dict[str, Any], acct: str,
                 sid: str, broker_files=None) -> Optional[str]:
    """A description of the arrival send `sid` of `acct` is paired with
    (None: not paired) — what `--set` says before a decision on a
    matched send is accepted."""
    accts = crypto_accounts(cfg)
    present = None
    if broker_files is not None:
        present = {(a, b) for a, fs in broker_files.items() for b, _p in fs}
    rows = load_transfer_rows(report_rows_root / "work", accts, present)
    assign_send_ids(rows)
    unpaired = {(a, k) for a in accts for k, rec in load_decisions(
        report_rows_root / "inputs" / a / MANIFEST_NAME)["sends"].items()
        if rec.get("unpair")}
    _u, pairs = match_transfers(rows, unpaired)
    for o, i in pairs:
        if o["account"] == acct and o["sid"] == sid:
            return (f"{_summary(o)} arrived as {fmt_qty(i['quantity'])} "
                    f"{i['symbol']} on "
                    f"{_EXCH_NAME.get(i['exchange'], i['exchange'])} "
                    f"({i['account']}) {i['date']} {i['time']}")
    return None


def network_fees(pairs, acct: str, rates: "Rates", usd_price,
                 country: str,
                 decisions: Optional[Dict[str, Any]] = None
                 ) -> List[Dict[str, Any]]:
    """The network fees hidden in matched sends of `acct`, as sales.

    A matched send that ARRIVED SHORT, from an exchange whose export
    states no fee, lost the difference to the network fee (a Coinbase
    Send: the fee is inside the sent quantity, Kraken credits the rest).
    Those coins paid for a service — a disposition at fair value in both
    countries, booked like the Kraken parser's own withdrawal fee
    (`<txid>-fee`; tax-logic CA-CRYPTO-06 / US-CRYPTO-05, audit R1-26,
    owner decision). A send whose fee the ledger states is already
    booked by the parser; a stablecoin's fee is US-dollar cash in a
    Canada project (CA-CRYPTO-02) and property, at par, in a US one.
    A hand price saved for the `-fee` id (`--set ID-fee=fee --price P`)
    values it when the lookup cannot (re-audit A2-0240)."""
    decisions = decisions or {}
    out: List[Dict[str, Any]] = []
    for o, i in pairs:
        if o["account"] != acct or o["fee"]:
            continue
        if is_cash_stablecoin(o["symbol"], o["exchange"]) \
                and country != "usa":
            continue
        gap = round(-o["quantity"] - i["quantity"], 12)
        if gap <= 1e-12:
            continue
        fee_send = dict(o, quantity=-gap)
        fid = (o.get("sid") or send_id(o["exchange"], o["date"], o["time"],
                                       o["symbol"], o["quantity"])) + "-fee"
        manual = (decisions.get(fid) or {}).get("price")
        fv = fair_value(fee_send, rates, usd_price, manual,
                        stable_cash=country != "usa")
        out.append({
            "id": fid,
            "account": acct, "exchange": o["exchange"], "kind": o["kind"],
            "date": o["date"], "time": o["time"], "symbol": o["symbol"],
            "quantity": gap, "sent": -o["quantity"],
            "arrived": i["quantity"],
            "arrived_on": _EXCH_NAME.get(i["exchange"], i["exchange"]),
            "summary": _summary(o), "network_fee": True,
            "fair_value": fv,
            "tt": tt_line(fee_send, fv, rates.base) if fv else None,
        })
    return out


# ------------------------------------------------------------- .tt file
def tt_entries(acct_doc: Dict[str, Any]) -> Tuple[List[Dict[str, Any]],
                                                  List[Dict[str, Any]]]:
    """(entries to write, entries that cannot be priced): every
    gift/payment send and every network fee hidden in a matched send
    (``network_fees``). A decision the country refuses (``refused``) is
    never written. Each priced entry is written on its own: one that
    cannot be priced no longer holds back the rest (re-audit A2-0240)."""
    todo = [e for e in acct_doc["sends"]
            if e["decision"] in DISPOSING and not e["stable"]
            and not e.get("refused")]
    todo += list(acct_doc.get("network_fees") or [])
    return ([e for e in todo if e["tt"]], [e for e in todo if not e["tt"]])


def tt_want_ids(acct_doc: Dict[str, Any]) -> set:
    """The ids a current crypto_sends.tt records (the checklist's
    staleness check; no prices needed)."""
    return ({e["id"] for e in acct_doc["sends"]
             if e["decision"] in DISPOSING and not e["stable"]
             and not e.get("refused")}
            | {e["id"] for e in acct_doc.get("network_fees") or []})


def refused_entries(acct_doc: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Saved decisions the project's country refuses (a US gift)."""
    return [e for e in acct_doc["sends"] if e.get("refused")]


def render_tt(account: str, entries: List[Dict[str, Any]],
              country: str = "canada") -> Optional[str]:
    if not entries:
        return None
    from taxjson.lib.country import canonical_country
    if canonical_country(country) == "usa":
        why = ["# Each line is a crypto send that left your ownership as a "
               "payment: a sale at",
               "# fair market value (a gift is not a sale for a US donor "
               "and is never written)."]
    else:
        why = ["# Each line is a crypto send that left your ownership: a "
               "gift or a payment is a",
               "# disposition at fair market value (a gift: ITA "
               "s.69(1)(b))."]
    if any(e.get("network_fee") for e in entries):
        why += ["# A `-fee` line is the network fee hidden in a send that "
                "arrived short on",
                "# another of your exchanges: the coins that did not "
                "arrive paid for a service,",
                "# a sale at fair value (as a Kraken withdrawal fee "
                "paid in the coin is)."]
    out = [GENERATED_MARK,
           f"# Source: inputs/{account}/{MANIFEST_NAME} (your decisions) — "
           f"`taxjson crypto-sends {account}` lists them.",
           *why,
           ""]
    for e in sorted(entries, key=lambda e: (e["date"], e["time"], e["id"])):
        if e.get("network_fee"):
            ex = _EXCH_NAME.get(e["exchange"], e["exchange"])
            out.append(f"# {e['id']}: network fee — {ex} {e['kind']} "
                       f"{e['date']} {e['time']} of {fmt_qty(e['sent'])} "
                       f"{e['symbol']}, {fmt_qty(e['arrived'])} arrived on "
                       f"{e['arrived_on']}")
            out.append(f"#   fair value {fmt_price(e['fair_value']['price'])} "
                       f"{e['fair_value'].get('currency', '')} per "
                       f"{e['symbol']}: {e['fair_value']['source']}")
            out.append(e["tt"])
            continue
        what = {"gift": "gift", "payment": "payment"}[e["decision"]]
        ex = _EXCH_NAME.get(e["exchange"], e["exchange"])
        out.append(f"# {e['id']}: {what} — {ex} {e['kind']} {e['date']} "
                   f"{e['time']} of {fmt_qty(e['quantity'])} {e['symbol']}")
        if e["fee_booked"]:
            out.append(f"#   the {fmt_qty(e['fee_booked'])} {e['symbol']} "
                       f"network fee is already booked from the ledger")
        out.append(f"#   fair value {fmt_price(e['fair_value']['price'])} "
                   f"{e['fair_value'].get('currency', '')} per "
                   f"{e['symbol']}: {e['fair_value']['source']}")
        if e.get("note"):
            out.append(f"#   note: {' '.join(str(e['note']).split())}")
        out.append(e["tt"])
    return "\n".join(out) + "\n"


def write_tt(path: Path, text: Optional[str]) -> str:
    """'written' | 'unchanged' | 'removed' | 'absent'. Refuses to touch
    a crypto_sends.tt it did not generate."""
    exists = path.is_file()
    if exists:
        cur = path.read_text(encoding="utf-8")
        if not cur.startswith(GENERATED_MARK):
            raise ValueError(
                f"{path} exists but was not generated by `taxjson "
                f"crypto-sends` — refusing to overwrite it. Rename it "
                f"(any other .tt name works) and re-run.")
        if text == cur:
            return "unchanged"
        if text is None:
            path.unlink()
            return "removed"
    elif text is None:
        return "absent"
    tmp = path.with_name(path.name + ".part")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, path)
    return "written"


def tt_ids(path: Path) -> Optional[set]:
    """Send ids recorded in a generated crypto_sends.tt (None: no file)."""
    if not path.is_file():
        return None
    ids = set()
    for ln in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^# ((?:kr|cb|[a-z]{2})-\d{8}T\d{6}-\S+): ", ln)
        if m:
            ids.add(m.group(1))
    return ids


def tt_stale_ids(acct_doc: Dict[str, Any], path: Path) -> List[str]:
    """Ids whose generated line in crypto_sends.tt is not the one the
    saved decision gives now: the id is missing or extra, or — when the
    fair value is known offline (a --price, the cached rates) — its
    BUYSELL line differs (a changed --price left the old sale booked
    while the id-only check said current, A2-1151)."""
    want = tt_want_ids(acct_doc)
    have = tt_ids(path) or set()
    stale = set(want ^ have)
    try:
        lines = set(path.read_text(encoding="utf-8").splitlines()) \
            if path.is_file() else set()
    except OSError:
        lines = set()
    for e in list(acct_doc["sends"]) + list(acct_doc.get("network_fees") or []):
        if e["id"] in want and e.get("tt") and e["tt"] not in lines:
            stale.add(e["id"])
    return sorted(stale)


def disposing_entries(acct_doc: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Every send crypto_sends.tt sells (priced or not): the decided
    gifts/payments and the network fees — what a hand-written .tt line
    must not sell again (duplicate_lines)."""
    return ([e for e in acct_doc["sends"]
             if e["decision"] in DISPOSING and not e["stable"]
             and not e.get("refused")]
            + list(acct_doc.get("network_fees") or []))


# A hand-written quantity this close to a generated one sells the same
# coins: a network fee folded in (-1000.01 for 1000), or the ledger
# quantity rounded (re-audit A2-0575 / A2-1005).
DUP_REL_TOL = 0.005


def _hand_qty_close(tok: str, q: float, want: float) -> bool:
    """Whether hand-written quantity `q` (token `tok`) is `want`."""
    frac = tok.lstrip("+-").replace(",", "").split(".")
    half_ulp = 0.5 * 10 ** -len(frac[1]) if len(frac) > 1 else 0.5
    return abs(q - want) <= max(want * DUP_REL_TOL, half_ulp) + 1e-12


def duplicate_lines(acct_dir: Path, entries: List[Dict[str, Any]]
                    ) -> List[Dict[str, Any]]:
    """Hand-written .tt lines that already sell what a generated
    crypto_sends.tt line sells — the same coin and about the same
    quantity (within DUP_REL_TOL, or the hand line's rounding) on the
    send's local date or the day either side (a hand line dated by the
    UTC stamp), on one line or split over several lines of one file —
    so booking both counts the disposition twice. Numbers are read the
    way convert-tt reads them ('-1,000' is 1000). Every account's
    folder under inputs/ is searched (one pool per coin across accounts
    in Canada). Each hit: {"file": path relative to the project,
    "line": 1-based, "id": send id, "timestamp": the send's date and
    time, "same_time": the .tt line has the send's exact time}. Nothing
    is deleted: which line to keep is the owner's call."""
    from taxjson.bin.taxjson_convert_tt import _tt_num
    hits: List[Dict[str, Any]] = []
    inputs = acct_dir.parent
    if not inputs.is_dir() or not entries:
        return hits

    def near(d1: str, d2: str) -> bool:
        try:
            a = datetime.strptime(d1, "%Y-%m-%d")
            b = datetime.strptime(d2, "%Y-%m-%d")
        except ValueError:
            return False
        return abs((a - b).days) <= 1

    for d in sorted(p for p in inputs.iterdir() if p.is_dir()):
        for p in sorted(d.iterdir()):
            if (not p.is_file() or p.suffix.lower() != ".tt"
                    or p.name == TT_NAME):
                continue
            try:
                text = p.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            lines = []
            for n, ln in enumerate(text.splitlines(), 1):
                tok = ln.split("#", 1)[0].split()
                if len(tok) < 5 or tok[0].upper() != "BUYSELL":
                    continue
                try:
                    q = _tt_num(tok[4])
                except ValueError:
                    continue
                if q < 0:
                    lines.append((n, tok, -q))
            for e in entries:
                sym = e["symbol"].upper()
                cand = [(n, tok, q) for n, tok, q in lines
                        if tok[3].upper() == sym and near(tok[1], e["date"])]
                found = [c for c in cand
                         if _hand_qty_close(c[1][4], c[2], e["quantity"])]
                if not found and len(cand) > 1:
                    tot = sum(q for _n, _t, q in cand)
                    if abs(tot - e["quantity"]) <= (e["quantity"]
                                                    * DUP_REL_TOL + 1e-12):
                        found = cand
                for n, tok, _q in found:
                    hits.append({
                        "file": f"{inputs.name}/{d.name}/{p.name}",
                        "line": n, "id": e["id"],
                        "timestamp": f"{e['date']} {e['time']}",
                        "same_time": (tok[1] == e["date"]
                                      and tok[2] == e["time"]),
                        "quantity": e["quantity"],
                        "symbol": e["symbol"]})
    return hits


# --------------------------------------------------------------- prompt
_ANSWERS = {"s": "self", "self": "self", "g": "gift", "gift": "gift",
            "p": "payment", "payment": "payment", "k": None, "skip": None,
            "": None}


def prompt_undecided(sends: List[Dict[str, Any]], manifest: Path,
                     ask: Callable[[str], str] = input,
                     say: Callable[[str], None] = None,
                     allow_gift: bool = True) -> int:
    """Ask once per undecided send; save each answer as it is given.
    Returns the number of decisions recorded."""
    if say is None:
        def say(msg: str) -> None:
            print(msg, file=sys.stderr)
    todo = [s for s in sends if not s.get("decision")]
    if not todo:
        return 0
    say(f"  {len(todo)} crypto send(s) left an exchange and did not "
        f"arrive on another one. For each: self = your own wallet (no "
        f"tax event); "
        + ("gift / payment = a disposition at fair value; " if allow_gift
           else "payment = a sale at fair value (a gift is not a sale "
                "for a US donor: answer self); ")
        + "skip = decide later (`taxjson crypto-sends`).")
    done = 0
    for s in todo:
        say(f"  {s['id']}  {s['summary']}")
        fv = s.get("fair_value")
        if fv:
            cur = fv.get("currency", "")
            say(f"      fair value {fmt_price(fv['price'])} {cur} per "
                f"{s.get('symbol', '')} = {fv['value']:.2f} {cur} "
                f"[{fv['source']}]")
        if s.get("stable"):
            fx = s.get("fx")
            say("      stablecoin (US-dollar cash in the books): a gift "
                "or payment is a currency disposition — no sale line"
                + (f"; FX gain {fx['gain']:+.2f}"
                   + (" (likely superficial)" if fx.get("superficial")
                      else "") if fx else ""))
        while True:
            try:
                raw = ask("      [s]elf / [g]ift / [p]ayment / s[k]ip? "
                          if allow_gift else
                          "      [s]elf / [p]ayment / s[k]ip? ")
            except EOFError:
                return done
            ans = (raw or "").strip().lower()
            if ans not in _ANSWERS:
                say("      answer s, g, p or k")
                continue
            dec = _ANSWERS[ans]
            if dec == "gift" and not allow_gift:
                say("      US: a gift is not a sale for the donor — "
                    "answer self or payment")
                continue
            break
        if dec:
            record_decision(manifest, s["id"], dec, summary=s["summary"])
            done += 1
    return done
