"""Crypto sends: is an outgoing crypto transfer a disposition?

The Kraken and Coinbase parsers keep every withdrawal / send / deposit
as TRANSFER custody evidence in the parse-stage sidecar
(work/<acct>_<broker>_transfers.json) — never in the books, because
moving coins between your own wallets is not a sale. A send that LEFT
your ownership (a gift, a payment for goods or services) is a
disposition at fair market value, and only the owner knows which it
was. This module:

  * pairs each send with its arrival on another exchange (a
    self-custody move, nothing to decide) and lists the rest;
  * keeps the owner's decision per send in inputs/<acct>/sends.json
    (`self` | `gift` | `payment`, plus a note), keyed by a stable id
    built from exchange, local date/time, coin and quantity (never a
    txid, refid or wallet address);
  * prices each send (the exchange's own spot price when the row has
    one; otherwise the Yahoo daily close fill-crypto uses, times the
    Bank of Canada rate of the send date) and renders the .tt line
    `BUYSELL <date> <time> <COIN> -<qty> CAD <price> <proceeds> 0`;
  * writes those lines for every gift/payment to ONE generated file,
    inputs/<acct>/crypto_sends.tt, so `taxjson run` books them;
  * for USD stablecoins (USDC/USDT/DAI, PYUSD/GUSD) — which the crypto
    books treat as US-dollar cash, so there is no coin position to sell
    — reports the currency gain instead: average CAD cost of the
    USD-cash/stablecoin pool (rebuilt from the ledgers) against the
    send-date value at the Bank of Canada rate.

The network fee a Kraken withdrawal charges in the coin is already
booked by the parser as its own disposition (`<txid>-fee`); the
sidecar quantity excludes it, so the lines here never count it again.
"""
from __future__ import annotations

import csv
import json
import math
import os
import re
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional, Tuple

MANIFEST_NAME = "sends.json"
TT_NAME = "crypto_sends.tt"
GENERATED_MARK = ("# GENERATED by `taxjson crypto-sends --write` — do not "
                  "edit; change a decision and re-write.")
DECISIONS = ("self", "gift", "payment")
DISPOSING = ("gift", "payment")
# Decisions a country refuses: a gift is a disposition at fair value
# only in Canada (ITA s.69(1)(b)); a US donor's gift is not a sale
# (lib/country.COMMAND_COUNTRY["crypto-sends:gift"]). Checked when the
# .tt is WRITTEN, not only at --set: a sends.json carried over from a
# Canada project, copied or hand-edited must never book a US gift
# (partition SPEC-01 / INPUTS-04).
REFUSED = {"usa": ("gift",)}


class RefusedDecision(ValueError):
    """A saved decision the project's country refuses (a US gift). The
    .tt is still written — WITHOUT the refused sends — so nothing books
    them; the caller stops with this message."""

# USD-pegged stablecoins the crypto books treat as US-dollar cash (the
# Kraken parser folds USDC/USDT/DAI to USD; the Coinbase parser also
# PYUSD/GUSD). A sale line for one would sell a position that does not
# exist.
STABLECOINS = frozenset({"USDC", "USDT", "DAI", "PYUSD", "GUSD"})
USD_FAMILY = STABLECOINS | {"USD"}

_EXCH_ABBR = {"kraken": "kr", "coinbase": "cb"}
_EXCH_NAME = {"kraken": "Kraken", "coinbase": "Coinbase"}
_CRYPTO_BROKERS = ("kraken", "coinbase")

# Send/arrival pairing: the arrival must land on another exchange (or
# account) within this window after the send (a little before too —
# exchange clocks disagree), with at most this share of the coins lost
# to the network fee, and never MORE coins than were sent.
MATCH_BEFORE = timedelta(minutes=10)
MATCH_AFTER = timedelta(days=3)
MATCH_MAX_LOSS = 0.10

# Superficial-loss window (ITA s.54): 30 days either side.
_SL_DAYS = 30


# ------------------------------------------------------------ formatting
def mask_ref(ref: Any) -> str:
    """First 2 characters + *** (the privacy rule for ids)."""
    s = str(ref or "").strip()
    if s.endswith("-xfer"):
        s = s[:-len("-xfer")]
    return (s[:2] + "***") if s else ""


def fmt_qty(q: float) -> str:
    """Plain decimal, no exponent, no trailing zeros (0.1, 56.821203563)."""
    s = f"{abs(float(q)):.12f}".rstrip("0").rstrip(".")
    return s or "0"


def fmt_price(p: float) -> str:
    """Six significant digits, no exponent: 387.813, 150000, 1.3611."""
    p = float(p)
    if p == 0 or not math.isfinite(p):
        return "0"
    decimals = max(6 - int(math.floor(math.log10(abs(p)))) - 1, 0)
    s = f"{round(p, decimals):.{decimals}f}"
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    return s


def send_id(exchange: str, date: str, time: str, symbol: str,
            qty: float) -> str:
    """Stable, typeable, private: kr-20260504T185014-TAO-0.1."""
    ex = _EXCH_ABBR.get(exchange, (exchange or "xx")[:2].lower())
    return (f"{ex}-{date.replace('-', '')}T{time.replace(':', '')}-"
            f"{symbol.upper()}-{fmt_qty(qty)}")


def _dt(row: Dict[str, Any]) -> datetime:
    return datetime.strptime(f"{row['date']} {row.get('time') or '00:00:00'}",
                             "%Y-%m-%d %H:%M:%S")


# ------------------------------------------------------------- evidence
def load_transfer_rows(cache: Path, accounts: Iterable[str]
                       ) -> List[Dict[str, Any]]:
    """TRANSFER evidence rows from the crypto sidecars of `accounts`."""
    rows: List[Dict[str, Any]] = []
    for acct in accounts:
        for broker in _CRYPTO_BROKERS:
            p = cache / f"{acct}_{broker}_transfers.json"
            if not p.is_file():
                continue
            try:
                doc = json.loads(p.read_text(encoding="utf-8"))
            except (OSError, ValueError) as e:
                raise ValueError(f"could not read {p.name}: {e}") from None
            meta = doc.get("metadata") or {}
            if meta.get("kind") != "transfer_sidecar":
                continue
            exch = str(meta.get("brokerage") or broker)
            for t in doc.get("transactions") or []:
                q = float(t.get("quantity") or 0.0)
                if not q or not t.get("date"):
                    continue
                desc = str(t.get("description") or "")
                fee = float(t.get("fee") or 0.0)
                # "(fee X CCY)" marks a fee in ANOTHER currency; a bare
                # fee is in the coin itself.
                fee_other = "(fee " in desc
                rows.append({
                    "account": acct,
                    "exchange": exch,
                    "date": str(t.get("date")),
                    "time": str(t.get("time") or "00:00:00"),
                    "symbol": str(t.get("symbol") or "").upper(),
                    "quantity": q,
                    "price": abs(float(t.get("price") or 0.0)),
                    "currency": str(t.get("currency") or "").upper(),
                    "fee": 0.0 if fee_other else abs(fee),
                    "kind": desc.split(" (fee ")[0] or "transfer",
                    "ref": mask_ref(t.get("id")),
                })
    return rows


def match_transfers(rows: List[Dict[str, Any]]
                    ) -> Tuple[List[Dict[str, Any]],
                               List[Tuple[Dict[str, Any], Dict[str, Any]]]]:
    """(unmatched sends, [(send, arrival)]). Each send is paired with at
    most one arrival and vice versa: same coin, another exchange or
    account, inside the time window, arrival <= sent and within the
    network-fee loss. Sends are taken in time order; each picks the
    closest-in-time candidate."""
    outs = sorted((r for r in rows if r["quantity"] < 0),
                  key=lambda r: (_dt(r), r["exchange"], r["symbol"]))
    ins = [r for r in rows if r["quantity"] > 0]
    used: set = set()
    unmatched: List[Dict[str, Any]] = []
    pairs: List[Tuple[Dict[str, Any], Dict[str, Any]]] = []
    for o in outs:
        o_dt, q_out = _dt(o), -o["quantity"]
        best = None
        best_key = None
        for i, r in enumerate(ins):
            if i in used or r["symbol"] != o["symbol"]:
                continue
            if r["exchange"] == o["exchange"] and r["account"] == o["account"]:
                continue
            delta = _dt(r) - o_dt
            if delta < -MATCH_BEFORE or delta > MATCH_AFTER:
                continue
            q_in = r["quantity"]
            if q_in > q_out * (1 + 1e-9) + 1e-12:
                continue
            if q_in < q_out * (1 - MATCH_MAX_LOSS):
                continue
            key = (abs(delta.total_seconds()), q_out - q_in)
            if best_key is None or key < best_key:
                best, best_key = i, key
        if best is None:
            unmatched.append(o)
        else:
            used.add(best)
            pairs.append((o, ins[best]))
    return unmatched, pairs


# ------------------------------------------------------------- manifest
def load_decisions(path: Path) -> Dict[str, Any]:
    if not path.is_file():
        return {"schema_version": 1, "sends": {}}
    try:
        doc = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        raise ValueError(f"{path} is not valid JSON ({e}) — fix or delete "
                         f"it (it holds your gift/payment/self decisions)."
                         ) from None
    if not isinstance(doc, dict) or not isinstance(doc.get("sends"), dict):
        raise ValueError(f"{path}: expected {{\"sends\": {{ID: {{...}}}}}}.")
    for sid, rec in doc["sends"].items():
        if not isinstance(rec, dict) or rec.get("decision") not in DECISIONS:
            raise ValueError(
                f"{path}: send {sid!r} has decision "
                f"{(rec or {}).get('decision') if isinstance(rec, dict) else rec!r}"
                f" — expected one of {', '.join(DECISIONS)}.")
    doc.setdefault("schema_version", 1)
    return doc


def save_decisions(path: Path, doc: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".part")
    tmp.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n",
                   encoding="utf-8")
    os.replace(tmp, path)


def record_decision(path: Path, sid: str, decision: str,
                    note: Optional[str] = None,
                    price: Optional[float] = None,
                    summary: str = "") -> None:
    if decision not in DECISIONS:
        raise ValueError(f"decision {decision!r} — expected one of "
                         f"{', '.join(DECISIONS)}")
    doc = load_decisions(path)
    rec = dict(doc["sends"].get(sid) or {})
    rec["decision"] = decision
    if summary:
        rec["summary"] = summary
    if note is not None:
        if note:
            rec["note"] = note
        else:
            rec.pop("note", None)
    if price is not None:
        rec["price"] = float(price)
    doc["sends"][sid] = rec
    save_decisions(path, doc)


# ---------------------------------------------------------------- rates
def load_rates(path: Path) -> Dict[str, Dict[str, Tuple[float, str]]]:
    """{currency: {date: (rate, source)}} from work/to_base.csv
    (`DATE TIME FROM TO RATE [SOURCE]`)."""
    out: Dict[str, Dict[str, Tuple[float, str]]] = {}
    if not path.is_file():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        parts = line.split()
        if len(parts) < 5 or not re.match(r"^\d{4}-\d{2}-\d{2}$", parts[0]):
            continue
        try:
            rate = float(parts[4])
        except ValueError:
            continue
        if not (rate > 0 and math.isfinite(rate)):
            continue
        out.setdefault(parts[2].upper(), {})[parts[0]] = (
            rate, parts[5].lower() if len(parts) > 5 else "")
    return out


class Rates:
    def __init__(self, table, base: str):
        self.table = table
        self.base = base.upper()
        self._sorted: Dict[str, List[str]] = {}

    def get(self, cur: str, on: str) -> Optional[Tuple[float, str, str]]:
        """(rate, rate date, label) of the latest rate on/before `on`."""
        cur = cur.upper()
        if cur == self.base:
            return 1.0, on, ""
        days = self.table.get(cur) or {}
        if cur not in self._sorted:
            self._sorted[cur] = sorted(days)
        keys = self._sorted[cur]
        import bisect
        i = bisect.bisect_right(keys, on)
        if i == 0:
            return None
        d = keys[i - 1]
        rate, src = days[d]
        label = {"boc": "Bank of Canada", "irs": "IRS"}.get(src, src or "")
        return rate, d, label


def _rate_text(cur: str, base: str, r: Tuple[float, str, str],
               on: str) -> str:
    rate, d, label = r
    who = f"{label} " if label else ""
    when = d if d == on else f"{d}, latest before {on}"
    return f"{who}{cur}/{base} {rate:g} ({when})"


# ---------------------------------------------------------------- prices
def yahoo_usd_price(project_root: Path) -> Callable[[str, str],
                                                    Tuple[Optional[float], str]]:
    """The fill-crypto price source: Yahoo `<id>-USD` daily close, the
    same cache (~/.crypto_price_cache.json) and the same symbol map
    (built-ins + the project's crypto_ticker.map). Offline
    (TAXJSON_OFFLINE) it answers from the cache only."""
    from taxjson.bin import fill_crypto_prices as F
    from taxjson.lib.offline import offline_enabled
    overrides = F.load_symbol_overrides([str(project_root)])
    state: Dict[str, Any] = {"cache": None}

    def lookup(symbol: str, day: str) -> Tuple[Optional[float], str]:
        ysym = overrides.get(symbol, symbol)
        if state["cache"] is None:
            state["cache"] = F.load_cache()
        cache = state["cache"]
        key = f"{ysym}-{day}"
        if key in cache and float(cache[key]) > 0:
            return float(cache[key]), ysym
        if offline_enabled():
            return None, ysym
        saved = dict(F.SYMBOL_OVERRIDES)
        F.SYMBOL_OVERRIDES.update(overrides)
        try:
            p = F.get_crypto_price(symbol, day)
        finally:
            F.SYMBOL_OVERRIDES.clear()
            F.SYMBOL_OVERRIDES.update(saved)
        if p and p > 0:
            cache[key] = p
            F.save_cache(cache)
            return float(p), ysym
        return None, ysym
    return lookup


def fair_value(send: Dict[str, Any], rates: Rates,
               usd_price: Optional[Callable[[str, str],
                                            Tuple[Optional[float], str]]],
               manual: Optional[float] = None) -> Optional[Dict[str, Any]]:
    """{'price': per coin in base, 'value', 'source'} or None (unpriced)."""
    base = rates.base
    sym, day, qty = send["symbol"], send["date"], -send["quantity"]
    ex = _EXCH_NAME.get(send["exchange"], send["exchange"])
    if manual is not None:
        price, src = float(manual), "entered by hand (--price)"
    elif sym in STABLECOINS:
        r = rates.get("USD", day)
        if r is None:
            return None
        price = r[0]
        src = (f"{sym} = 1 USD (stablecoins are US-dollar cash in the "
               f"books)" + ("" if base == "USD" else
                            f" x {_rate_text('USD', base, r, day)}"))
    elif send["price"] > 0:
        cur = send["currency"] or "USD"
        cur = "USD" if cur in STABLECOINS else cur
        if cur == base:
            price = send["price"]
            src = f"{ex} spot price on the send row ({base})"
        else:
            r = rates.get(cur, day)
            if r is None:
                return None
            price = send["price"] * r[0]
            src = (f"{ex} spot price {fmt_price(send['price'])} {cur} x "
                   f"{_rate_text(cur, base, r, day)}")
    else:
        if usd_price is None:
            return None
        usd, ysym = usd_price(sym, day)
        if not usd:
            return None
        if base == "USD":
            price = usd
            src = f"Yahoo {ysym}-USD daily close {fmt_price(usd)} USD ({day})"
        else:
            r = rates.get("USD", day)
            if r is None:
                return None
            price = usd * r[0]
            src = (f"Yahoo {ysym}-USD daily close {fmt_price(usd)} USD "
                   f"({day}) x {_rate_text('USD', base, r, day)}")
    p = float(fmt_price(price))
    return {"price": p, "value": round(qty * p, 2), "currency": base,
            "source": src}


def tt_line(send: Dict[str, Any], fv: Dict[str, Any], base: str) -> str:
    qty = -send["quantity"]
    return (f"BUYSELL {send['date']} {send['time']} {send['symbol']} "
            f"-{fmt_qty(qty)} {base} {fmt_price(fv['price'])} "
            f"{round(qty * fv['price'], 2):.2f} 0")


# ------------------------------------------------ USD / stablecoin pool
def _kraken_norm(asset: str, fold: bool = False) -> str:
    from taxjson.lib.brokerages.kraken import _normalize_asset
    return _normalize_asset(asset, fold_stable=fold)


def kraken_pool_flows(path: Path) -> List[Dict[str, Any]]:
    """USD-family cash flows from one Kraken LEDGER export, one per
    refid: {'dt', 'units' (signed), 'cad' (CAD leg of the same refid)}.
    Custody rows (withdrawal/deposit/p2p/hybridearnwithdrawal of a
    non-fiat asset) are skipped — they come from the sidecar with their
    pairing — and so are Earn-wallet shuffles (never left the account)."""
    from taxjson.lib.brokerages.kraken import (
        _classify_header, _fee_ccy, _lower_row, _STAKING_WALLET_MOVES,
        _FIAT_CURRENCIES)
    from taxjson.lib.brokerages._crypto_common import (strict_money,
                                                       utc_to_local)
    with open(path, "r", encoding="utf-8-sig") as f:
        if _classify_header(f.readline()) != "ledgers":
            return []
        f.seek(0)
        groups: Dict[str, Dict[str, Any]] = {}
        order: List[str] = []
        for n, raw in enumerate(csv.DictReader(f)):
            row = _lower_row(raw)
            type_ = (row.get("type") or "").strip().lower()
            sub = (row.get("subtype") or "").strip().lower()
            name = _kraken_norm(row.get("asset") or "")
            if (type_ in ("withdrawal", "deposit", "hybridearnwithdrawal")
                    or (type_ == "transfer" and sub == "transferpeertopeer")
                    ) and name not in _FIAT_CURRENCIES:
                continue            # custody evidence -> the sidecar
            if ((type_ == "earn" and sub in ("allocation", "deallocation",
                                             "autoallocation"))
                    or (type_.startswith("hybridearn"))
                    or (type_ == "transfer" and sub in _STAKING_WALLET_MOVES)):
                continue            # own-wallet shuffle
            amount = strict_money(row.get("amount"), "amount", path.name)
            fee = abs(strict_money(row.get("fee"), "fee", path.name))
            fccy = _fee_ccy(row, name)
            fam = ((amount if name in USD_FAMILY else 0.0)
                   - (fee if fccy in USD_FAMILY else 0.0))
            cad = ((amount if name == "CAD" else 0.0)
                   - (fee if fccy == "CAD" else 0.0))
            if not fam and not cad:
                continue
            ref = (row.get("refid") or "").strip() or f"#{n}"
            g = groups.get(ref)
            if g is None:
                t = (row.get("time") or "").split(".")[0]
                dt = utc_to_local(datetime.strptime(t, "%Y-%m-%d %H:%M:%S"))
                g = groups[ref] = {"dt": dt, "units": 0.0, "cad": 0.0,
                                   "what": f"Kraken {type_}"}
                order.append(ref)
            g["units"] += fam
            g["cad"] += cad
    return [groups[r] for r in order if abs(groups[r]["units"]) > 1e-9]


def coinbase_pool_flows(path: Path) -> List[Dict[str, Any]]:
    """Stablecoin flows from one Coinbase export: buys/sells/rewards of
    a stablecoin, and the stablecoin leg of Advanced Trades on X-USDC
    and of Converts. Send/Receive come from the sidecar."""
    from taxjson.lib.brokerages import coinbase as C
    from taxjson.lib.brokerages._crypto_common import (strict_money,
                                                       utc_to_local)
    out: List[Dict[str, Any]] = []
    with open(path, "r", encoding="utf-8-sig") as f:
        rows = list(csv.reader(f))
    hmap: Dict[str, int] = {}
    start = None
    for i, row in enumerate(rows):
        if row and "timestamp" in [c.lower().strip() for c in row]:
            raw = {c.lower().strip(): j for j, c in enumerate(row)}
            for field, names in C._HEADER_SYNONYMS.items():
                for nm in names:
                    if nm in raw:
                        hmap[field] = raw[nm]
                        break
            start = i + 1
            break
    if start is None:
        return out

    def col(row, key):
        j = hmap.get(key, -1)
        return row[j] if 0 <= j < len(row) else ""

    def num(row, key):
        return strict_money(col(row, key), key, path.name)

    for row in rows[start:]:
        if not row or len(row) < 3:
            continue
        type_raw = col(row, "transaction type").strip()
        tl = type_raw.lower()
        if tl in ("send", "receive"):
            continue
        stamp = col(row, "timestamp").replace(" UTC", "").strip()
        dt = None
        for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%dT%H:%M:%SZ"):
            try:
                dt = datetime.strptime(stamp, fmt)
                break
            except ValueError:
                continue
        if dt is None:
            continue
        dt = utc_to_local(dt)
        asset = col(row, "asset").strip().upper()
        cur = (col(row, "price currency") or "USD").strip().upper()
        notes = col(row, "notes") or ""
        if asset in STABLECOINS:
            qty = abs(num(row, "quantity transacted"))
            if "convert" in tl:
                m = C._CONVERT_NOTES_RE.search(notes)
                if m and m.group(4).upper() not in USD_FAMILY:
                    out.append({"dt": dt, "units": -float(
                        m.group(1).replace(",", "")), "cad": 0.0,
                        "what": "Coinbase Convert"})
                continue
            if C._STAKING_RE.search(type_raw):
                out.append({"dt": dt, "units": qty, "cad": 0.0,
                            "what": f"Coinbase {type_raw}"})
            elif C._BUY_RE.search(type_raw):
                total = abs(num(row, "total")) if col(row, "total") else 0.0
                out.append({"dt": dt, "units": qty,
                            "cad": -total if cur == "CAD" else 0.0,
                            "what": f"Coinbase {type_raw}"})
            elif C._SELL_RE.search(type_raw):
                out.append({"dt": dt, "units": -qty, "cad": 0.0,
                            "what": f"Coinbase {type_raw}"})
            continue
        m = C._ADV_NOTES_RE.search(notes)
        if m and m.group(5).upper() in STABLECOINS:
            n = float(m.group(4).replace(",", ""))
            out.append({"dt": dt,
                        "units": -n if m.group(1).lower() == "bought" else n,
                        "cad": 0.0, "what": f"Coinbase {type_raw}"})
            continue
        if "convert" in tl:
            m = C._CONVERT_NOTES_RE.search(notes)
            if m and m.group(4).upper() in STABLECOINS:
                out.append({"dt": dt,
                            "units": float(m.group(3).replace(",", "")),
                            "cad": 0.0, "what": "Coinbase Convert"})
    return out


def usd_pool(flows: List[Dict[str, Any]], transfers: List[Dict[str, Any]],
             pairs, unmatched_ids: Dict[int, str], rates: Rates
             ) -> Dict[str, Any]:
    """Walk the USD-cash/stablecoin pool (average cost, ITA s.47) and
    value every unmatched stablecoin send against it.

    Acquisitions: a CAD leg in the same ledger entry is the exact cost
    (a CAD->USDC conversion); anything else (USD from a crypto sale, a
    stablecoin reward, a deposit from outside) costs units x the rate of
    the day. A send paired with its arrival only loses the network fee;
    an unmatched send leaves at average cost and, when it is a
    stablecoin, its FX gain is value - ACB."""
    base = rates.base
    events: List[Tuple[datetime, int, str, Dict[str, Any]]] = []
    for f in flows:
        events.append((f["dt"], 1, "flow", f))
    paired = {id(o): i for o, i in pairs}
    for t in transfers:
        if t["symbol"] not in USD_FAMILY:
            continue
        if t["quantity"] > 0:
            if any(i is t for i in paired.values()):
                continue
            events.append((_dt(t), 1, "in", t))
        else:
            events.append((_dt(t), 2, "out", t))
    events.sort(key=lambda e: (e[0], e[1]))
    units = cost = 0.0
    overdrafts = 0
    unrated = 0
    acq_dates: List[str] = []
    after: List[Tuple[str, float]] = []
    results: Dict[str, Dict[str, Any]] = {}

    def rate(day: str) -> Optional[float]:
        r = rates.get("USD", day)
        return r[0] if r else None

    def dispose(n: float, day: str) -> Tuple[float, float]:
        """Remove n units; returns (acb, overdraft units)."""
        nonlocal units, cost, overdrafts
        covered = min(n, units)
        acb = 0.0
        if covered > 0:
            avg = cost / units
            acb = covered * avg
            units -= covered
            cost -= acb
            if units < 1e-9:
                units, cost = 0.0, 0.0
        short = n - covered
        if short > 1e-6:
            overdrafts += 1
        return acb, max(short, 0.0)

    for dt, _o, kind, e in events:
        day = dt.strftime("%Y-%m-%d")
        if kind in ("flow", "in"):
            n = e["units"] if kind == "flow" else e["quantity"]
            if n > 0:
                if kind == "flow" and e.get("cad", 0.0) < 0:
                    c = -e["cad"]
                else:
                    r = rate(day)
                    if r is None:
                        unrated += 1
                        continue
                    c = n * r
                units += n
                cost += c
                acq_dates.append(day)
            else:
                dispose(-n, day)
        else:                                            # an out-leg
            q = -e["quantity"]
            if id(e) in paired:
                lost = q - paired[id(e)]["quantity"]
                if lost > 0:
                    dispose(lost, day)
            else:
                acb, short = dispose(q, day)
                r = rate(day)
                sid = unmatched_ids.get(id(e))
                if sid and e["symbol"] in STABLECOINS and r is not None:
                    acb += short * r      # overdraft: zero gain on it
                    value = q * r
                    results[sid] = {"units": q, "rate": r,
                                    "value": round(value, 2),
                                    "acb": round(acb, 2),
                                    "gain": round(value - acb, 2),
                                    "overdrawn": short > 1e-6}
            if e.get("fee"):
                dispose(e["fee"], day)
        after.append((day, units))

    # Superficial-loss flag (s.54): a loss, the same property bought
    # within 30 days either side, still held on day 30.
    for sid, res in results.items():
        res["superficial"] = False
        if res["gain"] >= 0:
            continue
        send_day = next(t for t in transfers
                        if unmatched_ids.get(id(t)) == sid)["date"]
        d0 = datetime.strptime(send_day, "%Y-%m-%d")
        lo = (d0 - timedelta(days=_SL_DAYS)).strftime("%Y-%m-%d")
        hi = (d0 + timedelta(days=_SL_DAYS)).strftime("%Y-%m-%d")
        if not any(lo <= d <= hi for d in acq_dates):
            continue
        held = 0.0
        for d, u in after:
            if d <= hi:
                held = u
        res["superficial"] = held > 1e-9
    return {"results": results, "overdrafts": overdrafts,
            "unrated": unrated, "units_now": round(units, 6),
            "avg_cost": (round(cost / units, 6) if units > 1e-9 else None),
            "base": base}


# --------------------------------------------------------------- report
def _summary(s: Dict[str, Any]) -> str:
    ex = _EXCH_NAME.get(s["exchange"], s["exchange"])
    return (f"{ex} {s['kind']} {s['date']} {s['time']} "
            f"{fmt_qty(-s['quantity'])} {s['symbol']}")


def crypto_accounts(cfg: Dict[str, Any]) -> List[str]:
    return [n for n, a in (cfg.get("accounts") or {}).items()
            if (a or {}).get("crypto")]


def build_report(root: Path, cfg: Dict[str, Any],
                 broker_files: Optional[Dict[str, List[Tuple[str, Path]]]]
                 = None,
                 usd_price=None, want: Optional[str] = None,
                 with_pool: bool = True) -> Dict[str, Any]:
    """Everything `crypto-sends` shows, per crypto account.
    `broker_files` ({acct: [(broker, csv)]}) feeds the stablecoin pool;
    None skips it (the checklist needs only the decisions)."""
    settings = cfg.get("settings") or {}
    from taxjson.lib.country import home_currency, settings_country
    country = settings_country(settings)
    base = str(settings.get("base_currency")
               or home_currency(country)).upper()
    cache = root / "work"
    accts = crypto_accounts(cfg)
    rows = load_transfer_rows(cache, accts)
    unmatched, pairs = match_transfers(rows)
    rates = Rates(load_rates(cache / "to_base.csv"), base)
    ids: Dict[int, str] = {}
    for s in unmatched:
        ids[id(s)] = send_id(s["exchange"], s["date"], s["time"],
                             s["symbol"], s["quantity"])
    pool = None
    if with_pool and broker_files is not None and base != "USD" and any(
            s["symbol"] in STABLECOINS for s in unmatched):
        flows: List[Dict[str, Any]] = []
        for acct in accts:
            for broker, p in broker_files.get(acct, []):
                if broker == "kraken":
                    flows += kraken_pool_flows(p)
                elif broker == "coinbase":
                    flows += coinbase_pool_flows(p)
        pool = usd_pool(flows, rows, pairs, ids, rates)
    out: Dict[str, Any] = {"base_currency": base, "country": country,
                           "accounts": {}}
    for acct in accts:
        if want and acct != want:
            continue
        man_path = root / "inputs" / acct / MANIFEST_NAME
        decisions = load_decisions(man_path)["sends"]
        sends = []
        for s in sorted((s for s in unmatched if s["account"] == acct),
                        key=lambda s: (_dt(s), ids[id(s)])):
            sid = ids[id(s)]
            rec = decisions.get(sid) or {}
            if not rec and s["kind"].lower().startswith("hybridearn"):
                # Kraken Hybrid Earn: the coins leave the spot ledger for
                # Kraken's Earn product and keep earning rewards for you —
                # still your property. Decided automatically; --set
                # overrides it.
                rec = {"decision": "self", "auto": True,
                       "note": "Kraken Hybrid Earn: still yours "
                               "(automatic)"}
            stable = s["symbol"] in STABLECOINS
            fv = fair_value(s, rates, usd_price, rec.get("price"))
            entry = {
                "id": sid, "account": acct, "exchange": s["exchange"],
                "kind": s["kind"], "date": s["date"], "time": s["time"],
                "symbol": s["symbol"], "quantity": -s["quantity"],
                "fee_booked": s["fee"], "ref": s["ref"],
                "summary": _summary(s), "stable": stable,
                "decision": rec.get("decision"), "note": rec.get("note", ""),
                "auto": bool(rec.get("auto")),
                "fair_value": fv, "tt": None, "fx": None,
            }
            if rec.get("decision") in REFUSED.get(country, ()):
                entry["refused"] = (
                    f"{sid} is saved as `{rec['decision']}`, which a US "
                    f"project refuses: a gift is not a sale for a US donor "
                    f"(the recipient takes over your basis). It is NOT "
                    f"booked — record it as `self` (no tax event) or, if "
                    f"you were paid, `payment`: `taxjson crypto-sends "
                    f"{acct} --set {sid}=self`")
            if not stable and fv is not None:
                entry["tt"] = tt_line(s, fv, base)
            if stable and pool is not None:
                entry["fx"] = pool["results"].get(sid)
            sends.append(entry)
        live = {e["id"] for e in sends}
        matched = sum(1 for o, _i in pairs if o["account"] == acct)
        out["accounts"][acct] = {
            "sends": sends,
            "matched": matched,
            "undecided": sum(1 for e in sends if not e["decision"]),
            "orphans": sorted(k for k in decisions if k not in live),
            "manifest": str(man_path),
            "tt_file": str(root / "inputs" / acct / TT_NAME),
        }
    if pool is not None:
        out["pool"] = {k: v for k, v in pool.items() if k != "results"}
    return out


# ------------------------------------------------------------- .tt file
def tt_entries(acct_doc: Dict[str, Any]) -> Tuple[List[Dict[str, Any]],
                                                  List[Dict[str, Any]]]:
    """(entries to write, gift/payment sends that cannot be priced).
    A decision the country refuses (``refused``) is never written."""
    todo = [e for e in acct_doc["sends"]
            if e["decision"] in DISPOSING and not e["stable"]
            and not e.get("refused")]
    return ([e for e in todo if e["tt"]], [e for e in todo if not e["tt"]])


def refused_entries(acct_doc: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Saved decisions the project's country refuses (a US gift)."""
    return [e for e in acct_doc["sends"] if e.get("refused")]


def render_tt(account: str, entries: List[Dict[str, Any]],
              country: str = "canada") -> Optional[str]:
    if not entries:
        return None
    from taxjson.lib.country import canonical_country
    if canonical_country(country) == "usa":
        why = ["# Each line is a crypto send that left your ownership as a "
               "payment: a sale at",
               "# fair market value (a gift is not a sale for a US donor "
               "and is never written)."]
    else:
        why = ["# Each line is a crypto send that left your ownership: a "
               "gift or a payment is a",
               "# disposition at fair market value (a gift: ITA "
               "s.69(1)(b))."]
    out = [GENERATED_MARK,
           f"# Source: inputs/{account}/{MANIFEST_NAME} (your decisions) — "
           f"`taxjson crypto-sends {account}` lists them.",
           *why,
           ""]
    for e in sorted(entries, key=lambda e: (e["date"], e["time"], e["id"])):
        what = {"gift": "gift", "payment": "payment"}[e["decision"]]
        ex = _EXCH_NAME.get(e["exchange"], e["exchange"])
        out.append(f"# {e['id']}: {what} — {ex} {e['kind']} {e['date']} "
                   f"{e['time']} of {fmt_qty(e['quantity'])} {e['symbol']}")
        if e["fee_booked"]:
            out.append(f"#   the {fmt_qty(e['fee_booked'])} {e['symbol']} "
                       f"network fee is already booked from the ledger")
        out.append(f"#   fair value {fmt_price(e['fair_value']['price'])} "
                   f"{e['fair_value'].get('currency', '')} per "
                   f"{e['symbol']}: {e['fair_value']['source']}")
        if e.get("note"):
            out.append(f"#   note: {' '.join(str(e['note']).split())}")
        out.append(e["tt"])
    return "\n".join(out) + "\n"


def write_tt(path: Path, text: Optional[str]) -> str:
    """'written' | 'unchanged' | 'removed' | 'absent'. Refuses to touch
    a crypto_sends.tt it did not generate."""
    exists = path.is_file()
    if exists:
        cur = path.read_text(encoding="utf-8")
        if not cur.startswith(GENERATED_MARK):
            raise ValueError(
                f"{path} exists but was not generated by `taxjson "
                f"crypto-sends` — refusing to overwrite it. Rename it "
                f"(any other .tt name works) and re-run.")
        if text == cur:
            return "unchanged"
        if text is None:
            path.unlink()
            return "removed"
    elif text is None:
        return "absent"
    tmp = path.with_name(path.name + ".part")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, path)
    return "written"


def tt_ids(path: Path) -> Optional[set]:
    """Send ids recorded in a generated crypto_sends.tt (None: no file)."""
    if not path.is_file():
        return None
    ids = set()
    for ln in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^# ((?:kr|cb|[a-z]{2})-\d{8}T\d{6}-\S+): ", ln)
        if m:
            ids.add(m.group(1))
    return ids


def duplicate_lines(acct_dir: Path, entries: List[Dict[str, Any]]
                    ) -> List[Dict[str, Any]]:
    """Hand-written .tt lines that already sell what a generated
    crypto_sends.tt line sells — the same coin and quantity on the same
    date — so booking both counts the disposition twice. Every account's
    folder under inputs/ is searched (one pool per coin across accounts
    in Canada). Each hit: {"file": path relative to the project,
    "line": 1-based, "id": send id, "timestamp": the send's date and
    time, "same_time": the .tt line has the send's exact time}. Nothing
    is deleted: which line to keep is the owner's call."""
    hits: List[Dict[str, Any]] = []
    inputs = acct_dir.parent
    if not inputs.is_dir():
        return hits
    want: Dict[Tuple[str, str, float], Dict[str, Any]] = {
        (e["date"], e["symbol"].upper(), round(e["quantity"], 10)): e
        for e in entries}
    if not want:
        return hits
    for d in sorted(p for p in inputs.iterdir() if p.is_dir()):
        for p in sorted(d.iterdir()):
            if (not p.is_file() or p.suffix.lower() != ".tt"
                    or p.name == TT_NAME):
                continue
            try:
                text = p.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            for n, ln in enumerate(text.splitlines(), 1):
                tok = ln.split("#", 1)[0].split()
                if len(tok) < 5 or tok[0].upper() != "BUYSELL":
                    continue
                try:
                    q = float(tok[4])
                except ValueError:
                    continue
                e = want.get((tok[1], tok[3].upper(), round(-q, 10)))
                if q < 0 and e is not None:
                    hits.append({
                        "file": f"{inputs.name}/{d.name}/{p.name}",
                        "line": n, "id": e["id"],
                        "timestamp": f"{e['date']} {e['time']}",
                        "same_time": tok[2] == e["time"],
                        "quantity": e["quantity"],
                        "symbol": e["symbol"]})
    return hits


# --------------------------------------------------------------- prompt
_ANSWERS = {"s": "self", "self": "self", "g": "gift", "gift": "gift",
            "p": "payment", "payment": "payment", "k": None, "skip": None,
            "": None}


def prompt_undecided(sends: List[Dict[str, Any]], manifest: Path,
                     ask: Callable[[str], str] = input,
                     say: Callable[[str], None] = None,
                     allow_gift: bool = True) -> int:
    """Ask once per undecided send; save each answer as it is given.
    Returns the number of decisions recorded."""
    if say is None:
        def say(msg: str) -> None:
            print(msg, file=sys.stderr)
    todo = [s for s in sends if not s.get("decision")]
    if not todo:
        return 0
    say(f"  {len(todo)} crypto send(s) left an exchange and did not "
        f"arrive on another one. For each: self = your own wallet (no "
        f"tax event); "
        + ("gift / payment = a disposition at fair value; " if allow_gift
           else "payment = a sale at fair value (a gift is not a sale "
                "for a US donor: answer self); ")
        + "skip = decide later (`taxjson crypto-sends`).")
    done = 0
    for s in todo:
        say(f"  {s['id']}  {s['summary']}")
        fv = s.get("fair_value")
        if fv:
            cur = fv.get("currency", "")
            say(f"      fair value {fmt_price(fv['price'])} {cur} per "
                f"{s.get('symbol', '')} = {fv['value']:.2f} {cur} "
                f"[{fv['source']}]")
        if s.get("stable"):
            fx = s.get("fx")
            say("      stablecoin (US-dollar cash in the books): a gift "
                "or payment is a currency disposition — no sale line"
                + (f"; FX gain {fx['gain']:+.2f}"
                   + (" (likely superficial)" if fx.get("superficial")
                      else "") if fx else ""))
        while True:
            try:
                raw = ask("      [s]elf / [g]ift / [p]ayment / s[k]ip? "
                          if allow_gift else
                          "      [s]elf / [p]ayment / s[k]ip? ")
            except EOFError:
                return done
            ans = (raw or "").strip().lower()
            if ans not in _ANSWERS:
                say("      answer s, g, p or k")
                continue
            dec = _ANSWERS[ans]
            if dec == "gift" and not allow_gift:
                say("      US: a gift is not a sale for the donor — "
                    "answer self or payment")
                continue
            break
        if dec:
            record_decision(manifest, s["id"], dec, summary=s["summary"])
            done += 1
    return done
